////////////////////////////////////////////////////
// More details at
//      http://www.flyOnSpeed.org
//      and
//      https://github.com/flyonspeed/OnSpeed-Gen3/

// OnSpeed Wifi - Wifi file server, config manager and debug display for ONSPEED Gen 2 v2,v3 boxes.

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

#include <log/LogMeta.h>
#include <log/LogMetaFile.h>

#include <Arduino.h>
#include <buildinfo.h>

#include <WiFi.h>               // https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi
#include <WiFiClient.h>
#include <WiFiAP.h>

#include <HTTP_Method.h>
#include <WebServer.h>          // https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer

#include <DNSServer.h>          // https://github.com/espressif/arduino-esp32/tree/master/libraries/DNSServer

#include <ESPmDNS.h>

#include <Update.h>             // https://github.com/espressif/arduino-esp32/tree/master/libraries/Update

#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>

#include "src/Globals.h"

#include "src/web_server/ApiHandlers.h"

using onspeed::accelPitch;
using onspeed::accelRoll;
using onspeed::ft2m;
using onspeed::inhg2mb;

#include "Web/html_header.h"
#include "Web/html_stubs.h"
#include "Web/legacy_pages.h"
#include "Web/static_app_js.h"
#include "Web/static_app_css.h"
// Auto-generated by scripts/embed_sim_for_firmware.sh.  Pre-build hook
// regenerates only when M5 sim sources are newer than the headers.

// Structures
// ----------

typedef struct
  {
  char filename[11];
  long filesize;
  } filetype;

// Module variables
// ----------------

// DNS server to handle domain names instead of raw IP addresses
DNSServer           DnsServer;

// Config web server
WebServer           CfgServer(80);

const char*     szSSID     = "OnSpeed";
const char*     szPassword = "angleofattack";

String      pageHeader;
String      pageFooter="</body></html>";

// Variables used for upload
bool        bUploadedConfigStringGood;
SemaphoreHandle_t uploadMutex;

// GLOBALS
//String sVersion = String("4.0.0 beta");

// Function prototypes
// -------------------
void HandleIndex();
void HandleFavicon();
void HandleReboot();
void HandleLive();
void HandleIndexer();
void HandleConfig();
void HandleConfigSave();
void HandleDefaultConfig();
void HandleConfigUpload();
void HandleFinalUpload();
void HandleSensorConfig();
void HandleCalWizardPage();
void HandleFormat();
void HandleLogs();
void HandleDelete();
void HandleDeleteBulk();
void HandleDownload();
void HandleWifiReflash();
void HandleUpgrade();
void HandleUpgradeSuccess();
void HandleUpgradeFailure();

// Static asset handlers (served with ETag caching)

// Shared Preact bundle handlers — content-hashed URLs, immutable
// Cache-Control.  Match by path prefix `/static/app-`.
void HandleStaticAppJs();
void HandleStaticAppCss();
static void ServePageStub(const char* stub);

// Indexer tab — embeds the M5 sim WASM, fed by the binary
// display-serial frames broadcast on port 81's WebSocket.

// Returns true if a 304 Not Modified was sent (caller should return early).
bool SendWithETag(const char* contentType);


// Reject filenames that contain path-traversal sequences, slashes, or
// characters outside the expected set for SD-card files. Used by
// /download, /delete, /delete-bulk. Does NOT restrict by extension —
// the /logs page shows all SD-card files (logs + config backups +
// boot_log.txt + whatever the user puts there), so all of them need
// to be downloadable and deletable. Security boundary is the character
// allow-list and the .. check, which together prevent path traversal.
static bool IsSafeLogFilename(const String& s)
    {
    if (s.length() == 0 || s.length() > 32) return false;
    if (s.indexOf('/')  >= 0) return false;
    if (s.indexOf('\\') >= 0) return false;
    if (s.indexOf("..") >= 0) return false;
    for (size_t i = 0; i < s.length(); i++)
        {
        char c = s.charAt(i);
        if (!(isalnum((unsigned char)c) || c == '_' || c == '.' || c == '-')) return false;
        }
    return true;
    }

// Returns true if `sFilename` is the currently-active log file (the CSV
// that LogSensor has open for writing). Deleting it would orphan the
// write handle and silently lose data, so delete handlers skip it.
static bool IsActiveLogFile(const String& sFilename)
    {
    const char* szActiveBase = g_LogSensor.ActiveBaseName();
    if (!szActiveBase || szActiveBase[0] == '\0') return false;
    String sActive = String(szActiveBase) + ".csv";
    return sFilename.equalsIgnoreCase(sActive);
    }

// Maximum number of flap positions accepted from a config-save POST.
// Matches MAX_AOA_CURVES in OnSpeedTypes.h (architecture limit).
static constexpr int kMaxFlapPositions = MAX_AOA_CURVES;

// ----------------------------------------------------------------------------

// Service the configuration web CfgServer.

void CfgWebServerPoll()
    {
    CfgServer.handleClient();
    DnsServer.processNextRequest();
    }

// ----------------------------------------------------------------------------

void CfgWebServerInit()
    {
    uploadMutex = xSemaphoreCreateMutex();

    // WIFI INIT
    g_Log.print(MsgLog::EnWebServer, MsgLog::EnDebug, "Starting Access Point");

    WiFi.mode(WIFI_AP);

    //WiFi.disconnect();
    delay(10);
    WiFi.setTxPower(WIFI_POWER_11dBm);
    WiFi.softAP(szSSID, szPassword);

    // Wait after init softAP
    delay(100);


    IPAddress    Ip(192, 168,   0, 1);
    IPAddress NMask(255, 255, 255, 0);

    WiFi.softAPConfig(Ip, Ip, NMask);
    IPAddress myIP = WiFi.softAPIP();
    g_Log.print("AP IP address: ");
    g_Log.println(myIP.toString().c_str());

    delay(100);

    // Connect URL to handler routine.  Six legacy pages (/, /reboot,
    // /format, /upgrade, /logs, /calwiz GET) now serve a Preact stub
    // and run their UI from the shared bundle.  /sensorconfig still
    // renders inline HTML — it lands on the Preact bundle in PR 5
    // alongside the read-side /api/sensors snapshot.  The legacy
    // POST handlers (/aoaconfigsave, /upload, /delete, /delete-bulk,
    // /download) are unchanged; the Preact pages talk to /api/* for
    // JSON and to /upload + /download directly for file streaming.
    CfgServer.on("/",                HTTP_GET,  HandleIndex);
    CfgServer.on("/favicon.ico",     HTTP_GET,  HandleFavicon);
    CfgServer.on("/reboot",          HTTP_GET,  HandleReboot);
    CfgServer.on("/live",            HTTP_GET,  HandleLive);
    CfgServer.on("/indexer",         HTTP_GET,  HandleIndexer);
    CfgServer.on("/aoaconfig",       HTTP_GET,  HandleConfig);
    CfgServer.on("/aoaconfigsave",   HTTP_POST, HandleConfigSave);
    CfgServer.on("/defaultconfig",   HTTP_GET,  HandleDefaultConfig);
    CfgServer.on("/aoaconfigupload", HTTP_POST, HandleFinalUpload, HandleConfigUpload);
    CfgServer.on("/sensorconfig",    HTTP_GET,  HandleSensorConfig);
    CfgServer.on("/calwiz",          HTTP_GET,  HandleCalWizardPage);
    CfgServer.on("/format",          HTTP_GET,  HandleFormat);
    CfgServer.on("/logs",            HTTP_GET,  HandleLogs);
    CfgServer.on("/delete",          HTTP_GET,  HandleDelete);
    CfgServer.on("/delete-bulk",     HTTP_POST, HandleDeleteBulk);
    CfgServer.on("/download",        HTTP_GET,  HandleDownload);

//    CfgServer.on("/wifireflash",     HTTP_GET,  HandleWifiReflash);
    CfgServer.on("/upgrade",         HTTP_GET,  HandleUpgrade);

    // ------------------------------------------------------------------
    // /api/* — JSON endpoints added in PR 2 of the web rewrite.  Sit
    // alongside the legacy form-encoded routes above; nothing legacy
    // changes.  See ApiHandlers.cpp for the implementations.
    // ------------------------------------------------------------------
    CfgServer.on("/api/sample/aoa",        HTTP_GET,  onspeed::api::HandleApiSampleAoa);
    CfgServer.on("/api/sample/flaps-raw",  HTTP_GET,  onspeed::api::HandleApiSampleFlapsRaw);
    CfgServer.on("/api/sample/volume",     HTTP_GET,  onspeed::api::HandleApiSampleVolume);
    CfgServer.on("/api/sample/pfwd",       HTTP_GET,  onspeed::api::HandleApiSamplePfwd);
    CfgServer.on("/api/sample/p45",        HTTP_GET,  onspeed::api::HandleApiSampleP45);

    CfgServer.on("/api/audiotest",         HTTP_POST, onspeed::api::HandleApiAudioTestStart);
    CfgServer.on("/api/audiotest/stop",    HTTP_POST, onspeed::api::HandleApiAudioTestStop);
    CfgServer.on("/api/audiotest/status",  HTTP_GET,  onspeed::api::HandleApiAudioTestStatus);
    CfgServer.on("/api/vnochime/test",     HTTP_POST, onspeed::api::HandleApiVnoChimeTest);

    CfgServer.on("/api/logs",              HTTP_GET,  onspeed::api::HandleApiLogs);
    CfgServer.on("/api/logs/delete-bulk",  HTTP_POST, onspeed::api::HandleApiLogsDeleteBulk);

    CfgServer.on("/api/format",            HTTP_POST, onspeed::api::HandleApiFormat);
    CfgServer.on("/api/format/status",     HTTP_GET,  onspeed::api::HandleApiFormatStatus);
    CfgServer.on("/api/reboot",            HTTP_POST, onspeed::api::HandleApiReboot);

    CfgServer.on("/api/calwiz/state",      HTTP_GET,  onspeed::api::HandleApiCalwizState);
    CfgServer.on("/api/calwiz/save",       HTTP_POST, onspeed::api::HandleApiCalwizSave);

    CfgServer.on("/api/version",           HTTP_GET,  onspeed::api::HandleApiVersion);

    // Handling uploading firmware file
    CfgServer.on("/upload", HTTP_POST,
        []()
            {
            CfgServer.sendHeader("Connection", "close");
            if (Update.hasError()) HandleUpgradeFailure();
            else                   HandleUpgradeSuccess();
            //CfgServer.send(200, "text/plain", (Update.hasError()) ? "FAIL" : "OK");
            delay(5000);
//            ESP.restart();
            _softRestart();
            }, // end first lambda expression
        []()
            {
            HTTPUpload& upload = CfgServer.upload();
            if (upload.status == UPLOAD_FILE_START)
                {
                g_Log.printf(MsgLog::EnWebServer, MsgLog::EnDebug, "Update: %s\n", upload.filename.c_str());
                if (!Update.begin(UPDATE_SIZE_UNKNOWN))
                    { //start with max available size
                    //Update.printError(Serial);
                    }
                }
            else if (upload.status == UPLOAD_FILE_WRITE)
                {
                /* flashing firmware to ESP*/
                if (Update.write(upload.buf, upload.currentSize) != upload.currentSize)
                    {
                    //Update.printError(Serial);
                    }
                }
            else if (upload.status == UPLOAD_FILE_END)
                {
                if (Update.end(true))
                    { //true to set the size to the current progress
                    g_Log.printf(MsgLog::EnWebServer, MsgLog::EnDebug, "Update Success: %u\nRebooting...\n", upload.totalSize);
                    }
                else
                    {
                    //Update.printError(Serial);
                    }
                }
            } // end second lambda expression
        );
    // /static/app-<sha>.{js,css} prefix routing.  ESP32 WebServer's
    // `on()` API only matches exact paths, so the content-hashed URL
    // (`/static/app-3a7f81b2.js`) needs a custom dispatcher.  Anything
    // else falls through to a 404.
    CfgServer.onNotFound(
        []()
            {
            const String uri = CfgServer.uri();
            if (uri.startsWith("/static/app-"))
                {
                if (uri.endsWith(".js"))
                    {
                    HandleStaticAppJs();
                    return;
                    }
                if (uri.endsWith(".css"))
                    {
                    HandleStaticAppCss();
                    return;
                    }
                }
            CfgServer.send(404, "text/plain", "File Not Found");
            }
        );
    // Register request headers we need to inspect (ESP32 WebServer discards them by default)
    const char* headersToCollect[] = { "If-None-Match" };
    CfgServer.collectHeaders(headersToCollect, 1);

    // Start server
    CfgServer.begin();

    if (MDNS.begin("onspeed"))
        MDNS.addService("http", "tcp", 80);
    // DnsServer.start(53, "onspeed.local",  Ip);

    } // end setup()


// ----------------------------------------------------------------------------
// URL handlers
// ----------------------------------------------------------------------------

void UpdateHeader()
    {
    pageHeader = String(szHtmlHeader);

    // rewrite firmware in the html header
    //if (sVersion == "")
    //    sVersion = "UNKNOWN";

    pageHeader.replace("wifi_fw", String("OnSpeed Version: ") + BuildInfo::version);
    pageHeader.replace("{{appCssEtag}}", static_app_css_etag);

#if 0
    // Update wifi status in html header
    if (WiFi.status() == WL_CONNECTED)
        {
        pageHeader.replace("wifi_status","");
        pageHeader.replace("wifi_network",clientwifi_ssid);
        }
    else
        {
        pageHeader.replace("wifi_status","offline");
        pageHeader.replace("wifi_network","Not Connected");
        }
#endif
    }

// ----------------------------------------------------------------------------
// ETag caching helper.  Returns true if a 304 Not Modified was sent
// (meaning the caller should return immediately without building a page).
// Uses BuildInfo::version as the ETag value — changes only on firmware update.
// Cache-Control: no-cache means "store but always revalidate".

bool SendWithETag(const char* contentType)
    {
    String sETag = String("\"") + BuildInfo::version + "\"";
    if (CfgServer.hasHeader("If-None-Match") &&
        CfgServer.header("If-None-Match") == sETag)
        {
        CfgServer.send(304);
        return true;
        }
    CfgServer.sendHeader("ETag", sETag);
    CfgServer.sendHeader("Cache-Control", "no-cache");
    return false;
    }

// ----------------------------------------------------------------------------
// Static asset handlers — served from PROGMEM with ETag caching.
// After first load the browser caches them; subsequent requests get 304.
//
// Legacy /css/main.css was retired — pageHeader now links to the
// bundled /static/app-<sha>.css that the Preact pages also load, so
// firmware and dev-server share one stylesheet source.











void HandleIndex()
    {
    ServePageStub(htmlStub_home);
    }


// ----------------------------------------------------------------------------

void HandleFavicon()
    {
    CfgServer.send(404, "text/plain", "FileNotFound");
    }

// ----------------------------------------------------------------------------

void HandleReboot()
    {
    ServePageStub(htmlStub_reboot);
    }



// ----------------------------------------------------------------------------
// Per-page Preact stubs.  ServePageStub() emits the per-route HTML
// stub (a complete document; bundler-generated) with ETag caching.
// The stub references /static/app-<sha>.{js,css} which carry the
// PageShell + the page component.  No pageHeader/pageFooter concat —
// PageShell owns the nav.

static void ServePageStub(const char* stub)
    {
    if (SendWithETag("text/html"))
        return;
    // Substitute the `{{onspeedVersion}}` placeholder with the running
    // firmware's build version.  The stub embeds it in a
    // `<meta name="onspeed-version">` tag so PageShell can render the
    // header banner from first paint with no /api/version round-trip.
    // ETag is keyed on BuildInfo::version, so a firmware update
    // invalidates the cached substituted page.
    String sStub((const __FlashStringHelper*)stub);
    sStub.replace("{{onspeedVersion}}", BuildInfo::version);
    CfgServer.send(200, "text/html", sStub);
    }

// /live is gone — the new /indexer covers everything that page used
// to render (Mode 0 indexer + the data-fields panel for the legacy
// 13-row stat table).  Keep the route registered as a 302 redirect so
// pilot bookmarks from the legacy era still land on a working page.
void HandleLive()
    {
    CfgServer.sendHeader("Location", "/indexer", true);
    CfgServer.send(302, "text/plain", "");
    }

void HandleIndexer()
    {
    ServePageStub(htmlStub_indexer);
    }

// /calwiz GET serves the Preact wizard's page stub.  The wizard's
// write side targets POST /api/calwiz/save and read side targets
// GET /api/calwiz/state — both implemented in ApiHandlers.cpp.
void HandleCalWizardPage()
    {
    ServePageStub(htmlStub_calwiz);
    }

// ----------------------------------------------------------------------------
// Shared bundle handlers.  The path is content-hashed
// (/static/app-<etag>.js) so we can serve with `immutable` cache —
// the URL changes whenever the bundle content changes, so the
// browser never has to revalidate.  Returned bytes are gzip-compressed
// in PROGMEM and sent verbatim with `Content-Encoding: gzip`.

static void SendImmutableGzip(const uint8_t* data, size_t len,
                              const char* etag, const char* contentType)
    {
    String sETag = String("\"") + etag + "\"";
    if (CfgServer.hasHeader("If-None-Match") &&
        CfgServer.header("If-None-Match") == sETag)
        {
        CfgServer.send(304);
        return;
        }
    CfgServer.sendHeader("ETag", sETag);
    CfgServer.sendHeader("Cache-Control", "public, max-age=31536000, immutable");
    CfgServer.sendHeader("Content-Encoding", "gzip");
    CfgServer.send_P(200, contentType, (PGM_P)data, len);
    }

void HandleStaticAppJs()
    {
    SendImmutableGzip(static_app_js, static_app_js_len,
                      static_app_js_etag, static_app_js_content_type);
    }

void HandleStaticAppCss()
    {
    SendImmutableGzip(static_app_css, static_app_css_len,
                      static_app_css_etag, static_app_css_content_type);
    }

// ----------------------------------------------------------------------------

void HandleConfig()
    {
    // /aoaconfig: legacy form-driven page.  Source lives in real
    // files under tools/web/legacy-pages/; the bundler emits
    // legacy_aoaconfig_html (template), legacy_aoaconfig_js (button +
    // audio-test client logic), and legacy_aoaconfig_post_js (form
    // visibility toggles + setpoint helpers).  This handler loads the
    // template, runs Mustache-style {{name}} substitutions from
    // g_Config, and sends the result inside the standard
    // pageHeader / pageFooter wrap.  The form's POST target
    // (/aoaconfigsave -> HandleConfigSave) is unchanged.
    //
    // Behavior change vs the prior inline-string body: the FillInValue
    // / GetValue button helpers in the extracted JS now read JSON from
    // /api/sample/aoa, /api/sample/flaps-raw, /api/sample/volume and
    // POST /api/vnochime/test instead of GET /getvalue?name=…  (the
    // latter route landed deleted in PR 4 of the web rewrite).  The
    // form-submit contract is byte-identical to the prior page.

    UpdateHeader();

    String sPage;
    sPage.reserve(pageHeader.length() + 24576);
    sPage += pageHeader;

    String sBody = String((const __FlashStringHelper*)legacy_aoaconfig_html);

    // -- 1. Per-flap section: extract the FLAP_BLOCK_{START,END} block
    // from the template, repeat it once per g_Config.aFlaps entry with
    // per-flap substitutions, and splice the result back into the
    // template at the block's location.
    const char* kFlapStart = "<!-- FLAP_BLOCK_START -->";
    const char* kFlapEnd   = "<!-- FLAP_BLOCK_END -->";
    int iFlapStart = sBody.indexOf(kFlapStart);
    int iFlapEnd   = sBody.indexOf(kFlapEnd);
    if (iFlapStart < 0 || iFlapEnd < 0 || iFlapEnd <= iFlapStart)
        {
        // Template malformed; surface it as a 500.
        CfgServer.send(500, "text/plain", "aoaconfig template missing FLAP_BLOCK markers");
        return;
        }
    int iFlapBodyStart = iFlapStart + (int)strlen(kFlapStart);
    String sFlapTemplate = sBody.substring(iFlapBodyStart, iFlapEnd);

    String sFlapsRendered;
    sFlapsRendered.reserve(sFlapTemplate.length() * (g_Config.aFlaps.size() + 1));
    for (int iFlapIdx = 0; iFlapIdx < (int)g_Config.aFlaps.size(); iFlapIdx++)
        {
        const FOSConfig::SuFlaps& f = g_Config.aFlaps[iFlapIdx];
        String s = sFlapTemplate;
        s.replace("{{flap.idx}}",        String(iFlapIdx));
        s.replace("{{flap.label}}",      String(iFlapIdx + 1));
        s.replace("{{flap.degrees}}",    String(f.iDegrees));
        s.replace("{{flap.potPosition}}", String(f.iPotPosition));
        s.replace("{{flap.LDMAXAOA}}",       g_Config.ToString(f.fLDMAXAOA));
        s.replace("{{flap.OnSpeedFastAOA}}", g_Config.ToString(f.fONSPEEDFASTAOA));
        s.replace("{{flap.OnSpeedSlowAOA}}", g_Config.ToString(f.fONSPEEDSLOWAOA));
        s.replace("{{flap.StallWarnAOA}}",   g_Config.ToString(f.fSTALLWARNAOA));
        s.replace("{{flap.StallAOA}}",       g_Config.ToString(f.fSTALLAOA));
        s.replace("{{flap.ManAOA}}",         g_Config.ToString(f.fMANAOA));
        s.replace("{{flap.KFit}}",           g_Config.ToString(f.fKFit));
        s.replace("{{flap.Alpha0}}",         g_Config.ToString(f.fAlpha0));
        s.replace("{{flap.AlphaStall}}",     g_Config.ToString(f.fAlphaStall));
        s.replace("{{flap.curvePolySel}}", String(f.AoaCurve.iCurveType == 1 ? " selected" : ""));
        s.replace("{{flap.curveLogSel}}",  String(f.AoaCurve.iCurveType == 2 ? " selected" : ""));
        s.replace("{{flap.curveExpSel}}",  String(f.AoaCurve.iCurveType == 3 ? " selected" : ""));
        s.replace("{{flap.coeff0}}", g_Config.ToString(f.AoaCurve.afCoeff[0]));
        s.replace("{{flap.coeff1}}", g_Config.ToString(f.AoaCurve.afCoeff[1]));
        s.replace("{{flap.coeff2}}", g_Config.ToString(f.AoaCurve.afCoeff[2]));
        s.replace("{{flap.coeff3}}", g_Config.ToString(f.AoaCurve.afCoeff[3]));

        // Per-curve-type initial-render labels next to each
        // coefficient.  Match the legacy initial-render strings (which
        // differ slightly from the JS-driven re-render via
        // curveTypeChange — preserving the legacy bytes here).
        const char* p0 = "";
        const char* p1 = "";
        const char* p2 = "";
        const char* p3 = "";
        if (f.AoaCurve.iCurveType == 1)
            {
            p0 = " *X<sup>3</sup>+";
            p1 = " *X<sup>2</sup>+";
            p2 = "*X+";
            p3 = "";
            }
        else if (f.AoaCurve.iCurveType == 2)
            {
            p0 = " * 0 + ";
            p1 = " * 0 + ";
            p2 = "*ln(x)+ ";
            p3 = "";
            }
        else if (f.AoaCurve.iCurveType == 3)
            {
            p0 = " * 0 + ";
            p1 = " * 0 + ";
            p2 = "* e^ (";
            p3 = ") * x";
            }
        s.replace("{{flap.param0}}", p0);
        s.replace("{{flap.param1}}", p1);
        s.replace("{{flap.param2}}", p2);
        s.replace("{{flap.param3}}", p3);

        sFlapsRendered += s;
        }

    // Splice: keep everything before FLAP_BLOCK_START, drop the
    // markers + template, insert rendered flaps, keep everything after
    // FLAP_BLOCK_END.
    String sBefore = sBody.substring(0, iFlapStart);
    String sAfter  = sBody.substring(iFlapEnd + (int)strlen(kFlapEnd));
    sBody = sBefore + sFlapsRendered + sAfter;

    // -- 2. Replay-log file picker datalist.  Built from the SD card's
    // current file listing under xWriteMutex.
    String sReplayOptions;
    if (xSemaphoreTake(xWriteMutex, pdMS_TO_TICKS(100)))
        {
        SdFileSys::SuFileInfoList suFileList;
        if (g_SdFileSys.FileList(&suFileList))
            for (int iIdx = 0; iIdx < suFileList.size(); iIdx++)
                if (strcasecmp(suFileList[iIdx].szFileName +
                               strlen(suFileList[iIdx].szFileName) - 4,
                               ".csv") == 0)
                    sReplayOptions +=
                        "                    <option value=\"" +
                        String(suFileList[iIdx].szFileName) + "\">\n";
        xSemaphoreGive(xWriteMutex);
        }
    sBody.replace("{{replayLogFileOptions}}", sReplayOptions);

    // -- 3. Visibility-class style="display:..." snippets.
    auto displayBlock = [](bool show)
        {
        return String(show ? R"#(style="display:block")#" : R"#(style="display:none")#");
        };
    sBody.replace("{{replayLogFileStyle}}",
                  displayBlock(g_Config.suDataSrc.enSrc == SuDataSource::EnReplay));
    sBody.replace("{{casCurveVisibility}}", displayBlock(g_Config.bCasCurveEnabled));
    sBody.replace("{{loadLimitVisibility}}", displayBlock(g_Config.bOverGWarning));
    sBody.replace("{{vnoVisibility}}", displayBlock(g_Config.bVnoChimeEnabled));

    // Volume-control toggles split into three coupled markers: the
    // outer flex-col-N width on volumeControlDiv, plus the
    // visibility on the default-volume single field and the high/low
    // analog reads.
    sBody.replace("{{volumeControlWidth}}",
                  String(g_Config.bVolumeControl ? "9" : "6"));
    sBody.replace("{{defaultVolumeVisibility}}", displayBlock(!g_Config.bVolumeControl));
    sBody.replace("{{volumeLevelsVisibility}}",  displayBlock(g_Config.bVolumeControl));

    // -- 4. <option selected> markers.  Each select dropdown contributes
    // one marker per option; the matching one substitutes to " selected"
    // and the others to empty.
    auto sel = [](bool b) -> String { return b ? String(" selected") : String(""); };

    sBody.replace("{{aoaSmoothing}}",      String(g_Config.iAoaSmoothing));
    sBody.replace("{{pressureSmoothing}}", String(g_Config.iPressureSmoothing));

    sBody.replace("{{dataSrcSensorsSel}}",    sel(g_Config.suDataSrc.enSrc == SuDataSource::EnSensors));
    sBody.replace("{{dataSrcTestPotSel}}",    sel(g_Config.suDataSrc.enSrc == SuDataSource::EnTestPot));
    sBody.replace("{{dataSrcRangeSweepSel}}", sel(g_Config.suDataSrc.enSrc == SuDataSource::EnRangeSweep));
    sBody.replace("{{dataSrcReplaySel}}",     sel(g_Config.suDataSrc.enSrc == SuDataSource::EnReplay));
    sBody.replace("{{replayLogFileName}}",    String(g_Config.sReplayLogFileName.c_str()));

    sBody.replace("{{boomEnabledSel}}",         sel(g_Config.bReadBoom));
    sBody.replace("{{boomDisabledSel}}",        sel(!g_Config.bReadBoom));
    sBody.replace("{{boomChecksumEnabledSel}}", sel(g_Config.bBoomChecksum));
    sBody.replace("{{boomChecksumDisabledSel}}", sel(!g_Config.bBoomChecksum));
    sBody.replace("{{boomConvertRawSel}}",  sel(!g_Config.bBoomConvertData));
    sBody.replace("{{boomConvertConvSel}}", sel(g_Config.bBoomConvertData));

    sBody.replace("{{casCurveEnabledSel}}",  sel(g_Config.bCasCurveEnabled));
    sBody.replace("{{casCurveDisabledSel}}", sel(!g_Config.bCasCurveEnabled));
    sBody.replace("{{casCurveTypePolySel}}", sel(g_Config.CasCurve.iCurveType == 1));
    sBody.replace("{{casCurveTypeLogSel}}",  sel(g_Config.CasCurve.iCurveType == 2));
    sBody.replace("{{casCurveTypeExpSel}}",  sel(g_Config.CasCurve.iCurveType == 3));
    sBody.replace("{{casCurveCoeff0}}", g_Config.ToString(g_Config.CasCurve.afCoeff[0]));
    sBody.replace("{{casCurveCoeff1}}", g_Config.ToString(g_Config.CasCurve.afCoeff[1]));
    sBody.replace("{{casCurveCoeff2}}", g_Config.ToString(g_Config.CasCurve.afCoeff[2]));
    sBody.replace("{{casCurveCoeff3}}", g_Config.ToString(g_Config.CasCurve.afCoeff[3]));

    // CAS-curve initial-render labels.  Different from per-flap labels
    // by design (legacy bytes); see the per-flap loop above.
    const char* casP0 = "";
    const char* casP1 = "";
    const char* casP2 = "";
    const char* casP3 = "";
    if (g_Config.CasCurve.iCurveType == 1)
        {
        casP0 = " *X<sup>3</sup>+ ";
        casP1 = " *X<sup>2</sup>+ ";
        casP2 = " *X<sup></sup>+ ";
        casP3 = "";
        }
    else if (g_Config.CasCurve.iCurveType == 2)
        {
        casP0 = " * 0 + ";
        casP1 = " * 0 + ";
        casP2 = "*ln(x)+";
        casP3 = "";
        }
    else if (g_Config.CasCurve.iCurveType == 3)
        {
        casP0 = " * 0 + ";
        casP1 = " * 0 + ";
        casP2 = "* e^ (";
        casP3 = " * x)";
        }
    sBody.replace("{{casCurveParam0}}", casP0);
    sBody.replace("{{casCurveParam1}}", casP1);
    sBody.replace("{{casCurveParam2}}", casP2);
    sBody.replace("{{casCurveParam3}}", casP3);

    sBody.replace("{{portsOrUpSel}}",      sel(g_Config.sPortsOrientation == "UP"));
    sBody.replace("{{portsOrDownSel}}",    sel(g_Config.sPortsOrientation == "DOWN"));
    sBody.replace("{{portsOrLeftSel}}",    sel(g_Config.sPortsOrientation == "LEFT"));
    sBody.replace("{{portsOrRightSel}}",   sel(g_Config.sPortsOrientation == "RIGHT"));
    sBody.replace("{{portsOrForwardSel}}", sel(g_Config.sPortsOrientation == "FORWARD"));
    sBody.replace("{{portsOrAftSel}}",     sel(g_Config.sPortsOrientation == "AFT"));

    sBody.replace("{{boxOrUpSel}}",      sel(g_Config.sBoxtopOrientation == "UP"));
    sBody.replace("{{boxOrDownSel}}",    sel(g_Config.sBoxtopOrientation == "DOWN"));
    sBody.replace("{{boxOrLeftSel}}",    sel(g_Config.sBoxtopOrientation == "LEFT"));
    sBody.replace("{{boxOrRightSel}}",   sel(g_Config.sBoxtopOrientation == "RIGHT"));
    sBody.replace("{{boxOrForwardSel}}", sel(g_Config.sBoxtopOrientation == "FORWARD"));
    sBody.replace("{{boxOrAftSel}}",     sel(g_Config.sBoxtopOrientation == "AFT"));

    sBody.replace("{{readEfisEnabledSel}}",  sel(g_Config.bReadEfisData));
    sBody.replace("{{readEfisDisabledSel}}", sel(!g_Config.bReadEfisData));
    sBody.replace("{{efisDynonD10Sel}}", sel(g_Config.sEfisType == "DYNOND10"));
    sBody.replace("{{efisAdvancedSel}}", sel(g_Config.sEfisType == "ADVANCED"));
    sBody.replace("{{efisG5Sel}}",       sel(g_Config.sEfisType == "GARMING5"));
    sBody.replace("{{efisG3xSel}}",      sel(g_Config.sEfisType == "GARMING3X"));
    sBody.replace("{{efisVn300Sel}}",    sel(g_Config.sEfisType == "VN-300"));
    sBody.replace("{{efisVn100Sel}}",    sel(g_Config.sEfisType == "VN-100"));
    sBody.replace("{{efisMglSel}}",      sel(g_Config.sEfisType == "MGL"));

    sBody.replace("{{oatEnabledSel}}",  sel(g_Config.bOatSensor));
    sBody.replace("{{oatDisabledSel}}", sel(!g_Config.bOatSensor));

    sBody.replace("{{calSrcOnspeedSel}}",
                  sel(g_Config.sCalSource == "ONSPEED" || g_Config.sCalSource == ""));
    sBody.replace("{{calSrcEfisSel}}", sel(g_Config.sCalSource == "EFIS"));

    sBody.replace("{{ahrsMadgwickSel}}", sel(g_Config.iAhrsAlgorithm == 0));
    sBody.replace("{{ahrsEkf6Sel}}",     sel(g_Config.iAhrsAlgorithm == 1));

    sBody.replace("{{volumeEnabledSel}}",  sel(g_Config.bVolumeControl));
    sBody.replace("{{volumeDisabledSel}}", sel(!g_Config.bVolumeControl));
    sBody.replace("{{defaultVolume}}",     String(g_Config.iDefaultVolume));
    sBody.replace("{{volumeLowAnalog}}",   String(g_Config.iVolumeLowAnalog));
    sBody.replace("{{volumeHighAnalog}}",  String(g_Config.iVolumeHighAnalog));
    sBody.replace("{{muteAudioUnderIAS}}", String(g_Config.iMuteAudioUnderIAS));
    sBody.replace("{{audio3dEnabledSel}}",  sel(g_Config.bAudio3D));
    sBody.replace("{{audio3dDisabledSel}}", sel(!g_Config.bAudio3D));

    sBody.replace("{{overgEnabledSel}}",   sel(g_Config.bOverGWarning));
    sBody.replace("{{overgDisabledSel}}",  sel(!g_Config.bOverGWarning));
    sBody.replace("{{loadLimitPositive}}",   String(g_Config.fLoadLimitPositive, 2));
    sBody.replace("{{loadLimitNegative}}",   String(g_Config.fLoadLimitNegative, 2));
    sBody.replace("{{asymmetricGyroLimit}}", String(g_Config.fAsymmetricGyroLimit, 1));
    sBody.replace("{{asymmetricReduction}}", String(g_Config.fAsymmetricReduction, 3));

    sBody.replace("{{vnoChimeEnabledSel}}",  sel(g_Config.bVnoChimeEnabled));
    sBody.replace("{{vnoChimeDisabledSel}}", sel(!g_Config.bVnoChimeEnabled));
    sBody.replace("{{vno}}",               String(g_Config.iVno));
    sBody.replace("{{vnoChimeInterval}}",  String(g_Config.uVnoChimeInterval));

    sBody.replace("{{sdLoggingEnabledSel}}",  sel(g_Config.bSdLogging));
    sBody.replace("{{sdLoggingDisabledSel}}", sel(!g_Config.bSdLogging));
    sBody.replace("{{logRate50Sel}}",  sel(g_Config.iLogRate != 208));
    sBody.replace("{{logRate208Sel}}", sel(g_Config.iLogRate == 208));

    sBody.replace("{{serialOutG3xSel}}",
                  sel(g_Config.sSerialOutFormat == "G3X"));
    sBody.replace("{{serialOutOnspeedSel}}",
                  sel(g_Config.sSerialOutFormat == "ONSPEED" ||
                      g_Config.sSerialOutFormat == ""));

    sBody.replace("{{acGrossWeight}}",  String(g_Config.iAcGrossWeight));
    sBody.replace("{{acBestGlideIAS}}", String(g_Config.fAcBestGlideIAS));
    sBody.replace("{{acVfe}}",          String(g_Config.fAcVfe));
    // The Custom-G inputs always render the pilot's typed Custom
    // values, regardless of which radio is active.  That way Custom
    // values survive when the pilot tries a named category and saves
    // — the active fAcGlimit/fAcNegGlimit fields hold the named
    // preset, while fCustomAcGlimit/fCustomAcNegGlimit preserve what
    // the pilot would re-enter Custom mode with.  Negative G is
    // shown as a positive magnitude.
    sBody.replace("{{customAcGlimit}}",    String(g_Config.fCustomAcGlimit, 2));
    sBody.replace("{{customAcNegGlimit}}", String(fabsf(g_Config.fCustomAcNegGlimit), 2));

    {
    // A named category is "active" only when both the positive and the
    // negative limit match the preset's pair.  Either side off-preset
    // -> Custom.  Tolerance ±0.005 G matches the pre-existing positive
    // check, well below the input field's two-decimal precision.
    float fPos = g_Config.fAcGlimit;
    float fNeg = g_Config.fAcNegGlimit;
    auto matches = [](float a, float b) { return fabsf(a - b) <= 0.005f; };
    bool bIsNormal    = matches(fPos,  3.80f) && matches(fNeg, -1.52f);
    bool bIsUtility   = matches(fPos,  4.40f) && matches(fNeg, -1.76f);
    bool bIsAerobatic = matches(fPos,  6.00f) && matches(fNeg, -3.00f);
    bool bIsPreset    = bIsNormal || bIsUtility || bIsAerobatic;
    sBody.replace("{{glimitNormalChecked}}",    String(bIsNormal    ? " checked" : ""));
    sBody.replace("{{glimitUtilityChecked}}",   String(bIsUtility   ? " checked" : ""));
    sBody.replace("{{glimitAerobaticChecked}}", String(bIsAerobatic ? " checked" : ""));
    sBody.replace("{{glimitCustomChecked}}",    String(!bIsPreset   ? " checked" : ""));
    sBody.replace("{{glimitCustomDisplay}}",    String(bIsPreset    ? "display:none" : ""));
    }

    // -- 5. Inline scripts.  Substituted last so any { } in their body
    // doesn't trip earlier replace() passes.
    sBody.replace("{{aoaconfigJs}}",
                  String((const __FlashStringHelper*)legacy_aoaconfig_js));
    sBody.replace("{{aoaconfigPostJs}}",
                  String((const __FlashStringHelper*)legacy_aoaconfig_post_js));

    sPage += sBody;
    sPage += pageFooter;
    CfgServer.send(200, "text/html", sPage);
    } // end HandleConfig()


// ----------------------------------------------------------------------------

void HandleConfigSave()
    {
    bool    bDeleteFlap     = false;
    bool    rebootRequired  = false;
    String  errorMessage    = "";

    if (CfgServer.hasArg("aoaSmoothing"))
        {
        if (g_Config.iAoaSmoothing != CfgServer.arg("aoaSmoothing").toInt())
            rebootRequired = true;
        g_Config.iAoaSmoothing = CfgServer.arg("aoaSmoothing").toInt();
        }

    if (CfgServer.hasArg("pressureSmoothing"))
        {
        if (g_Config.iPressureSmoothing != CfgServer.arg("pressureSmoothing").toInt())
            rebootRequired = true;
        g_Config.iPressureSmoothing = CfgServer.arg("pressureSmoothing").toInt();
        }

    if (CfgServer.hasArg("dataSource"))
        {
//        if (g_Config.sDataSource != CfgServer.arg("dataSource"))
        if (String(g_Config.suDataSrc.toCStr()) != CfgServer.arg("dataSource"))
            rebootRequired = true;
//        g_Config.sDataSource = CfgServer.arg("dataSource");
        g_Config.suDataSrc.fromStrSet(CfgServer.arg("dataSource").c_str());
        }

    if (CfgServer.hasArg("logFileName"))
        g_Config.sReplayLogFileName = CfgServer.arg("logFileName").c_str();

#if 1
    // Build the new flap vector locally first.  Building locally and
    // swapping under `xAhrsMutex` means concurrent flight-path readers on
    // Core 1 (SensorIO::Read AOA snapshot, Audio.cpp::UpdateTones,
    // DisplaySerial::Write, DataServer::UpdateLiveDataJson, Flaps::Update)
    // either see the entirely-old or the entirely-new vector, and the old
    // buffer's destruction is deferred past the mutex release so any
    // in-flight reader has finished by then.
    std::vector<FOSConfig::SuFlaps> aNewFlaps;
    aNewFlaps.reserve(kMaxFlapPositions);
    int iFlapIdx = 0;
    while (iFlapIdx < kMaxFlapPositions &&
           CfgServer.hasArg("flapDegrees"+String(iFlapIdx)))
        {
        FOSConfig::SuFlaps  suFlaps;
        if (!CfgServer.hasArg("deleteFlapPos"+String(iFlapIdx)))
            {
            suFlaps.iDegrees     = CfgServer.arg("flapDegrees"+String(iFlapIdx)).toInt();
            suFlaps.iPotPosition = CfgServer.arg("flapPotPositions"+String(iFlapIdx)).toInt();

            suFlaps.fLDMAXAOA       = g_Config.ToFloat(CfgServer.arg("flapLDMAXAOA"+String(iFlapIdx)));
            suFlaps.fONSPEEDFASTAOA = g_Config.ToFloat(CfgServer.arg("flapONSPEEDFASTAOA"+String(iFlapIdx)));
            suFlaps.fONSPEEDSLOWAOA = g_Config.ToFloat(CfgServer.arg("flapONSPEEDSLOWAOA"+String(iFlapIdx)));
            suFlaps.fSTALLWARNAOA   = g_Config.ToFloat(CfgServer.arg("flapSTALLWARNAOA"+String(iFlapIdx)));
            suFlaps.fSTALLAOA       = g_Config.ToFloat(CfgServer.arg("flapSTALLAOA"+String(iFlapIdx)));
            suFlaps.fMANAOA         = g_Config.ToFloat(CfgServer.arg("flapMANAOA"+String(iFlapIdx)));
            suFlaps.fAlpha0         = g_Config.ToFloat(CfgServer.arg("flapAlpha0"+String(iFlapIdx)));
            suFlaps.fAlphaStall     = g_Config.ToFloat(CfgServer.arg("flapAlphaStall"+String(iFlapIdx)));
            suFlaps.fKFit           = g_Config.ToFloat(CfgServer.arg("flapKFit"+String(iFlapIdx)));

            suFlaps.AoaCurve.iCurveType = CfgServer.arg("aoaCurve"+String(iFlapIdx)+"Type").toInt();
            for (int iCoeffIdx=0; iCoeffIdx< MAX_CURVE_COEFF; iCoeffIdx++)
                suFlaps.AoaCurve.afCoeff[iCoeffIdx] = g_Config.ToFloat(CfgServer.arg("aoaCurve"+String(iFlapIdx)+"Coeff"+String(iCoeffIdx)));

            aNewFlaps.push_back(suFlaps);
            }
        else
            bDeleteFlap = true;

        iFlapIdx++;
        }

    std::sort(aNewFlaps.begin(), aNewFlaps.end(),
            [](FOSConfig::SuFlaps a, FOSConfig::SuFlaps b) { return a.iDegrees < b.iDegrees; } );

    // If the user deleted every flap row, the new vector is empty.
    // Every downstream reader (Audio.cpp, SensorIO.cpp, etc.)
    // dereferences aFlaps[g_Flaps.iIndex] without a bounds check, so
    // the vector must always have at least one entry.  Push a zeroed
    // default — the uncalibrated audio gate in ToneCalc keeps it
    // silent.
    bool bRestoredEmptyDefault = onspeed::config::EnsureAtLeastOneFlap(aNewFlaps);

    // Atomic swap under xAhrsMutex, and clamp g_Flaps.iIndex to the new
    // size in the same critical section.  Without the iIndex clamp, a
    // 4->2 flap shrink would leave iIndex pointing past end-of-vector
    // for up to a second (until the next Flaps::Update() tick), and any
    // reader that took xAhrsMutex during that window would see a stale
    // out-of-bounds index against a fresh new vector and have to
    // fail-silent on every snapshot until the index caught up.  Doing
    // the clamp here means by the time we release xAhrsMutex, both the
    // vector and the active index are mutually consistent.
    //
    // The old vector's storage is held by `aOldFlaps` and destroyed
    // only after the mutex is released and re-acquired by the AHRS
    // reseed below -- by then any reader on Core 1 that grabbed a
    // pointer into the old buffer has long since dropped it.
    std::vector<FOSConfig::SuFlaps> aOldFlaps;
    xSemaphoreTake(xAhrsMutex, portMAX_DELAY);
    g_Config.aFlaps.swap(aOldFlaps);          // park old data
    g_Config.aFlaps.swap(aNewFlaps);          // install new data
    if (g_Config.aFlaps.empty())
        g_Flaps.iIndex = 0;
    else
        g_Flaps.iIndex = constrain(g_Flaps.iIndex, 0, (int)g_Config.aFlaps.size() - 1);
    xSemaphoreGive(xAhrsMutex);
    // aOldFlaps and aNewFlaps go out of scope at function end -- by
    // then the AHRS reseed below has held xAhrsMutex again, providing
    // a second synchronization point with any reader that takes the
    // mutex.

    if (bRestoredEmptyDefault)
        {
        g_Log.println(MsgLog::EnConfig, MsgLog::EnWarning,
            "All flap positions were deleted; restoring a zeroed default. "
            "Calibrate before flying.");
        }
#endif

    // Read boom enabled/disabled
    if (CfgServer.hasArg("readBoom") && CfgServer.arg("readBoom")=="1") g_Config.bReadBoom = true;
    else                                                                g_Config.bReadBoom = false;

    // Boom checksum enabled/disabled
    if (CfgServer.hasArg("boomChecksum") && CfgServer.arg("boomChecksum")=="1") g_Config.bBoomChecksum = true;
    else                                                                        g_Config.bBoomChecksum = false;

    // Boom data conversion
    if (CfgServer.hasArg("boomConvertData") && CfgServer.arg("boomConvertData")=="1") g_Config.bBoomConvertData = true;
    else                                                                              g_Config.bBoomConvertData = false;

    if (CfgServer.hasArg("casCurveEnabled") && CfgServer.arg("casCurveEnabled")=="1") g_Config.bCasCurveEnabled = true;
    else                                                                              g_Config.bCasCurveEnabled = false;

    if (CfgServer.hasArg("casCurveType")) g_Config.CasCurve.iCurveType=CfgServer.arg("casCurveType").toInt();

    // cas Curve
    for (int curveIndex=0; curveIndex< MAX_CURVE_COEFF; curveIndex++)
        {
        g_Config.CasCurve.afCoeff[curveIndex]=g_Config.ToFloat(CfgServer.arg("casCurveCoeff"+String(curveIndex)));
        }

    // Track whether any AHRS-relevant input changed so we only reseed
    // the attitude filter when the new value differs from the old.  An
    // unconditional reseed in flight (e.g. saving an unrelated setting
    // like sdLogging or grossWeight) would re-snapshot Madgwick / EKF6
    // state from instantaneous, G-loaded accelerometer reads and snap
    // SmoothedPitch/Roll to wildly wrong values for several seconds.
    bool bAhrsInputChanged = false;

    // read portsOrientation
    if (CfgServer.hasArg("portsOrientation"))
        {
        const std::string sNew = CfgServer.arg("portsOrientation").c_str();
        if (sNew != g_Config.sPortsOrientation)
            bAhrsInputChanged = true;
        g_Config.sPortsOrientation = sNew;
        }

    // read boxtopOrientation
    if (CfgServer.hasArg("boxtopOrientation"))
        {
        const std::string sNew = CfgServer.arg("boxtopOrientation").c_str();
        if (sNew != g_Config.sBoxtopOrientation)
            bAhrsInputChanged = true;
        g_Config.sBoxtopOrientation = sNew;
        }

    // read efis enabled/disabled
    if (CfgServer.hasArg("readEfisData") && CfgServer.arg("readEfisData")=="1") g_Config.bReadEfisData=true;
    else                                                                        g_Config.bReadEfisData=false;

    // read efis Type
    if (CfgServer.hasArg("efisType")) g_Config.sEfisType=CfgServer.arg("efisType").c_str();

    // OAT sensor enabled/disabled
    if (CfgServer.hasArg("oatSensor") && CfgServer.arg("oatSensor")=="1") g_Config.bOatSensor = true;
    else                                                                   g_Config.bOatSensor = false;

    // read calibration source
    if (CfgServer.hasArg("calSource")) { g_Config.sCalSource=CfgServer.arg("calSource").c_str(); g_Config.bCalSourceEfis = (g_Config.sCalSource == "EFIS"); }

    // read AHRS algorithm
    if (CfgServer.hasArg("ahrsAlgorithm"))
        {
        const int iNew = CfgServer.arg("ahrsAlgorithm").toInt();
        if (iNew != g_Config.iAhrsAlgorithm)
            bAhrsInputChanged = true;
        g_Config.iAhrsAlgorithm = iNew;
        }

    // read volume control
    if (CfgServer.hasArg("volumeControl") && CfgServer.arg("volumeControl")=="1") g_Config.bVolumeControl=true;
    else                                                                          g_Config.bVolumeControl=false;

    //read volumePercent
    if (CfgServer.hasArg("defaultVolume")) g_Config.iDefaultVolume=CfgServer.arg("defaultVolume").toInt();

    // read low volume position
    if (CfgServer.hasArg("volumeLowAnalog")) g_Config.iVolumeLowAnalog=CfgServer.arg("volumeLowAnalog").toInt();

    // read high volume position
    if (CfgServer.hasArg("volumeHighAnalog")) g_Config.iVolumeHighAnalog=CfgServer.arg("volumeHighAnalog").toInt();

    // read muteAudioUnderIAS
    if (CfgServer.hasArg("muteAudioUnderIAS")) g_Config.iMuteAudioUnderIAS=CfgServer.arg("muteAudioUnderIAS").toInt();

    // read 3d audio enabled/disabled
    if (CfgServer.hasArg("audio3D") && CfgServer.arg("audio3D")=="1") g_Config.bAudio3D=true;
    else                                                              g_Config.bAudio3D=false;

    //overgWarning
    if (CfgServer.hasArg("overgWarning") && CfgServer.arg("overgWarning")=="1") g_Config.bOverGWarning=true;
    else                                                                        g_Config.bOverGWarning=false;

    // loadLimit
    if (CfgServer.hasArg("loadLimitPositive")) g_Config.fLoadLimitPositive= fabsf(CfgServer.arg("loadLimitPositive").toFloat());
    if (CfgServer.hasArg("loadLimitNegative")) g_Config.fLoadLimitNegative=-fabsf(CfgServer.arg("loadLimitNegative").toFloat());

    // Asymmetric G-limit tuning
    if (CfgServer.hasArg("asymmetricGyroLimit")) g_Config.fAsymmetricGyroLimit = fabsf(CfgServer.arg("asymmetricGyroLimit").toFloat());
    if (CfgServer.hasArg("asymmetricReduction")) { float f = CfgServer.arg("asymmetricReduction").toFloat(); g_Config.fAsymmetricReduction = constrain(f, 0.1f, 1.0f); }

    // vnochime
    if (CfgServer.hasArg("vnoChimeEnabled") && (CfgServer.arg("vnoChimeEnabled")=="1")) g_Config.bVnoChimeEnabled=true;
    else                                                                                g_Config.bVnoChimeEnabled=false;

    if (CfgServer.hasArg("Vno")) g_Config.iVno = CfgServer.arg("Vno").toInt();

    if (CfgServer.hasArg("vnoChimeInterval")) g_Config.uVnoChimeInterval=CfgServer.arg("vnoChimeInterval").toInt();

    // serialOutFormat
    if (CfgServer.hasArg("serialOutFormat")) { g_Config.sSerialOutFormat=CfgServer.arg("serialOutFormat").c_str(); g_Config.enSerialOutFormat = onspeed::config::OnSpeedConfig::ParseSerialFmt(g_Config.sSerialOutFormat); }

    //serialOutPort
//    if (CfgServer.hasArg("serialOutPort")) g_Config.sSerialOutPort=CfgServer.arg("serialOutPort");

    // sdLogging
    if (CfgServer.hasArg("sdLogging") && CfgServer.arg("sdLogging")=="1") g_Config.bSdLogging=true;
    else                                                                  g_Config.bSdLogging=false;

    // Logging rate
    if (CfgServer.hasArg("logRate")) { int v = CfgServer.arg("logRate").toInt(); g_Config.iLogRate = (v == 208) ? 208 : 50; }

    // Aircraft parameters
    if (CfgServer.hasArg("acGrossWeight"))  g_Config.iAcGrossWeight  =CfgServer.arg("acGrossWeight").toInt();
    if (CfgServer.hasArg("acBestGlideIAS")) g_Config.fAcBestGlideIAS =CfgServer.arg("acBestGlideIAS").toFloat();
    if (CfgServer.hasArg("acVfe"))          g_Config.fAcVfe          =CfgServer.arg("acVfe").toFloat();
    // acGlimit / acNegGlimit are the active values driven by the
    // selected radio: when a named category is active the JS handler
    // injects hidden inputs with the preset pair; when Custom is
    // active the JS re-enables the Custom inputs and they POST under
    // these names.  customAcGlimit / customAcNegGlimit always carry
    // the pilot's typed Custom values (independent of which radio is
    // active) so picking a named category and saving doesn't erase
    // the typed Custom pair.  Both pairs validated against sane
    // structural-category bounds; on out-of-range input, silently
    // keep the prior value — same convention as asymmetricReduction
    // above.
    if (CfgServer.hasArg("acGlimit"))
        {
        float f = fabsf(CfgServer.arg("acGlimit").toFloat());
        if (f > 0.0f && f <= 10.0f) g_Config.fAcGlimit = f;
        }
    if (CfgServer.hasArg("acNegGlimit"))
        {
        float f = fabsf(CfgServer.arg("acNegGlimit").toFloat());
        if (f > 0.0f && f <= 5.0f) g_Config.fAcNegGlimit = -f;
        }
    if (CfgServer.hasArg("customAcGlimit"))
        {
        float f = fabsf(CfgServer.arg("customAcGlimit").toFloat());
        if (f > 0.0f && f <= 10.0f) g_Config.fCustomAcGlimit = f;
        }
    if (CfgServer.hasArg("customAcNegGlimit"))
        {
        float f = fabsf(CfgServer.arg("customAcNegGlimit").toFloat());
        if (f > 0.0f && f <= 5.0f) g_Config.fCustomAcNegGlimit = -f;
        }

    // Handle Add Flap
    if (CfgServer.hasArg("addFlapPos"))
        {
        FOSConfig::SuFlaps      suFlaps;

        // Set default values for new flap setpoints and curves
        suFlaps.iDegrees        = 0;
        suFlaps.iPotPosition    = 0;
        suFlaps.fLDMAXAOA       = 0.0;
        suFlaps.fONSPEEDFASTAOA = 0.0;
        suFlaps.fONSPEEDSLOWAOA = 0.0;
        suFlaps.fSTALLWARNAOA   = 0.0;
        suFlaps.fSTALLAOA       = 0.0;
        suFlaps.fMANAOA         = 0.0;
        suFlaps.fAlpha0         = 0.0;
        suFlaps.fAlphaStall     = 0.0;
        suFlaps.fKFit           = 0.0;
        suFlaps.AoaCurve.iCurveType = 1;    // Default to polynomial curve
        for (int iCoeffIdx = 0; iCoeffIdx < MAX_CURVE_COEFF; iCoeffIdx++)
            suFlaps.AoaCurve.afCoeff[iCoeffIdx] = 0.0;

        // Add new flap curve
        g_Config.aFlaps.push_back(suFlaps);

        CfgServer.sendHeader("Location", "/aoaconfig");
        CfgServer.send(301, "text/html", "");
        } // end if add a new flap position

    // Handle Delete Flap
    else if (bDeleteFlap)
        {
        CfgServer.sendHeader("Location", "/aoaconfig");
        CfgServer.send(301, "text/html", "");
        }

    // Handle regular save
    else
        {
        String sPage;
        String sConfig = "";

        UpdateHeader();
        sPage.reserve(pageHeader.length() + 1024);
        sConfig.reserve(1024);
        sPage += pageHeader;

        // Save configuration. Maybe specify a config file name someday. Default for now.
        g_Config.SaveConfigurationToFile();

        // Warn if any flap position has out-of-order AOA setpoints
        for (size_t i = 0; i < g_Config.aFlaps.size(); i++)
            {
            String sErr = g_Config.aFlaps[i].SetpointOrderError().c_str();
            if (sErr.length() > 0)
                {
                sPage += "<br><br><b>WARNING:</b> Flap position " + String(g_Config.aFlaps[i].iDegrees)
                       + " degrees: " + sErr + "."
                         " Check the AOA setpoints on the configuration page and ensure they increase"
                         " from LDMAX through Stall. Audio behavior may be incorrect.";
                g_Log.printf(MsgLog::EnConfig, MsgLog::EnWarning,
                    "Flap %d deg: %s\n",
                    g_Config.aFlaps[i].iDegrees, sErr.c_str());
                }
            }

        sPage += "<br><br>Configuration saved.";
        if (rebootRequired)
            sPage += R"#(<br><br>Some of the changes require a system reboot to take effect.<br><br><br><a href="reboot?confirm=yes" class="button">Reboot Now</a>)#";
        sPage += pageFooter;

        CfgServer.send(200, "text/html", sPage);
        }

    // Reseed the AHRS only if an AHRS-relevant input actually changed.
    // The reseed re-snapshots attitude from current accelerometer reads,
    // which is exactly the wrong response in flight when the user just
    // toggled an unrelated checkbox like SD logging.  Take xAhrsMutex
    // either way for ConfigAxes() — IMU axis pointers are read by
    // ImuReadTask on Core 1 and must not tear during the reassignment.
    xSemaphoreTake(xAhrsMutex, portMAX_DELAY);
    g_pIMU->ConfigAxes();
    if (bAhrsInputChanged)
        g_AHRS.Init(kImuSampleRateHz);
    xSemaphoreGive(xAhrsMutex);

    } // end HandleConfigSave()

// ----------------------------------------------------------------------------

void HandleDefaultConfig()
    {
    String sPage;

    UpdateHeader();
    sPage.reserve(pageHeader.length() + 1024);
    sPage += pageHeader;

    if (CfgServer.hasArg("confirm") && CfgServer.arg("confirm")=="yes")
        {
        g_Config.LoadDefaultConfiguration();

        // Load default config
        CfgServer.sendHeader("Location", "/aoaconfig");
        CfgServer.send(302, "text/plain", "Redirect...");
        return;
        }
    else
        {
        // Display confirmation page
        sPage += R"#(
<br><br>
<p style="color:red">Confirm that you want to load the Default configuration. This will erase all of your current settings.</p>
<br><br><br>
<a href="/defaultconfig?confirm=yes" class="button">Load Default Config</a>
<a href="/aoaconfig">Cancel</a>
)#";
        }

    sPage += pageFooter;
    CfgServer.send(200, "text/html", sPage);
    } // end HandleDefaultConfig()


// ----------------------------------------------------------------------------

void HandleConfigUpload()
    {
    static String sUploadedConfigString = "";

    // Check if a configfile was uploaded
    HTTPUpload & uploadFile = CfgServer.upload();

    if (uploadFile.status == UPLOAD_FILE_START)
        {
        g_Log.print(MsgLog::EnWebServer, MsgLog::EnDebug, "UPLOAD Start\n");
        if (xSemaphoreTake(uploadMutex, portMAX_DELAY)) {
            sUploadedConfigString = "";
            bUploadedConfigStringGood = false;
            xSemaphoreGive(uploadMutex);
            }
        }

    else if (uploadFile.status == UPLOAD_FILE_WRITE)
        {
        if (xSemaphoreTake(uploadMutex, portMAX_DELAY)) {
            sUploadedConfigString.reserve(sUploadedConfigString.length() + uploadFile.currentSize);
            for (unsigned int i = 0; i < uploadFile.currentSize; i++) {
                sUploadedConfigString += char(uploadFile.buf[i]);
                }
            xSemaphoreGive(uploadMutex);
            }
        }

    else  if (uploadFile.status == UPLOAD_FILE_END)
        {
        g_Log.print(MsgLog::EnWebServer, MsgLog::EnDebug, "UPLOAD End\n");
        if (xSemaphoreTake(uploadMutex, portMAX_DELAY))
            {
            // Done uploading, parse and decode the uploaded configuration.
            // LoadConfigFromString() calls g_pIMU->ConfigAxes() and
            // g_AHRS.Init() internally, so hold xAhrsMutex to prevent
            // ImuReadTask from calling g_AHRS.Process() concurrently.
            xSemaphoreTake(xAhrsMutex, portMAX_DELAY);
            bUploadedConfigStringGood = g_Config.LoadConfigFromString(sUploadedConfigString);
            xSemaphoreGive(xAhrsMutex);

            if (bUploadedConfigStringGood)
                g_Log.print(MsgLog::EnWebServer, MsgLog::EnDebug, "UPLOAD Good Config String\n");
            else
                g_Log.print(MsgLog::EnWebServer, MsgLog::EnDebug, "UPLOAD Bad Config String\n");

            xSemaphoreGive(uploadMutex);
            } // end if got semaphore
        } // end UPLOAD_FILE_END

    } // end HandleConfigUpload()


// ----------------------------------------------------------------------------

void HandleFinalUpload()
    {
    String sPage;

    UpdateHeader();
    sPage.reserve(pageHeader.length() + 2048);
    sPage += pageHeader;

    if (xSemaphoreTake(uploadMutex, portMAX_DELAY))
        {
        if (bUploadedConfigStringGood == true)
            {
            // Display configuration page
            HandleConfig();
            }

        else
            {
            sPage += "<br><br>The uploaded file does not contain a valid configuration. Try another file.";
            sPage += pageFooter;
            CfgServer.send(200, "text/html", sPage);
            }

        xSemaphoreGive(uploadMutex);
        }

    }


// ----------------------------------------------------------------------------

void HandleSensorConfig()
    {
    String  sPage;
    UpdateHeader();
    sPage.reserve(pageHeader.length() + 8192);
    sPage += pageHeader;

    // First time through, no "yes" calibration confirm
    if (CfgServer.arg("confirm").indexOf("yes") < 0)
        {
        String sCurrentConfig = "";
        sCurrentConfig += "\n<table>\n";
        sCurrentConfig += "<tr><td style=\"padding-right: 20px;\">Pfwd Bias:</td><td>"                + String(g_Config.iPFwdBias)                 + "</td><td>Counts</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">P45 Bias:</td><td>"                 + String(g_Config.iP45Bias)                  + "</td><td>Counts</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Static Bias:</td><td>"              + String(g_Config.fPStaticBias)              + "</td><td>millibars</td></tr>\n";

        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">gx Bias:</td><td>"                  + String(g_Config.fGxBias)                   + "</td><td></td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">gy Bias:</td><td>"                  + String(g_Config.fGyBias)                   + "</td><td></td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">gz Bias:</td><td>"                  + String(g_Config.fGzBias)                   + "</td><td></td></tr>\n";

        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">IMU Pitch:</td><td>"                + String(g_pIMU->PitchAC())                  + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Pitch Bias:</td><td>"               + String(g_Config.fPitchBias)                + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Calculated True AC Pitch:</td><td>" + String(g_AHRS.PitchWithBias())             + "</td><td>Degrees</td></tr>\n";

        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">IMU Roll:</td><td>"                 + String(g_pIMU->RollAC())                   + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Roll Bias:</td><td>"                + String(g_Config.fRollBias)                 + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Calculated True AC Roll:</td><td>"  + String(g_AHRS.RollWithBias())              + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" </table>\n";

        // Determine default pitch/roll/palt values for the form.
        //
        // Pitch/roll: EFIS if fresh (< 2 s) and sentinels pass; otherwise the
        // OnSpeed AHRS reading. Both are honest references — pitch/roll bias
        // calibrates against gravity, which the AHRS already estimates.
        //
        // PAlt: external truth only. The OnSpeed static sensor is the
        // calibration target, so it is never a default. EFIS baro is used
        // only for EFIS types that actually carry static pressure on the
        // wire (Dynon, Garmin, MGL). VN-300 is GPS/INS with no air-data
        // channel — its `Palt` slot is never populated, so leave the field
        // blank and prompt the pilot to enter local field elevation.
        bool    bUseEfisAttitude = false;
        bool    bEfisHasPalt     = false;
        float   fDefPitch        = g_AHRS.PitchWithBias();
        float   fDefRoll         = g_AHRS.RollWithBias();
        String  sDefPalt         = "";          // blank → placeholder shown
        String  sPaltPlaceholder = "e.g. 1234"; // local field PAlt in feet

        if (g_Config.bReadEfisData &&
            (millis() - g_EfisSerial.uTimestamp < 2000) &&
            g_EfisSerial.suEfis.Pitch > -90 &&     // not the -100 invalid sentinel
            g_EfisSerial.suEfis.Roll  > -179)       // not the -180 invalid sentinel
            {
            fDefPitch        = g_EfisSerial.suEfis.Pitch;
            fDefRoll         = g_EfisSerial.suEfis.Roll;
            bUseEfisAttitude = true;

            // Positive list of EFIS types whose wire protocol carries static
            // pressure. A new non-baro EFIS added to the enum stays out of
            // this list by default and the PAlt field stays blank.
            const auto enType = g_EfisSerial.enType;
            const bool bEfisSuppliesBaro =
                (enType == EfisSerialPort::EnDynonSkyview) ||
                (enType == EfisSerialPort::EnDynonD10)     ||
                (enType == EfisSerialPort::EnGarminG5)     ||
                (enType == EfisSerialPort::EnGarminG3X)    ||
                (enType == EfisSerialPort::EnMglBinary);

            if (bEfisSuppliesBaro)
                {
                sDefPalt     = String(g_EfisSerial.suEfis.Palt);
                bEfisHasPalt = true;
                }
            }

        String sEfisNote = "";
        if (bUseEfisAttitude && bEfisHasPalt)
            sEfisNote = R"#(<p style="color:green"><b>EFIS data detected:</b> pitch, roll, and altitude pre-populated from EFIS. You can override if needed.</p>)#";
        else if (bUseEfisAttitude)
            sEfisNote = R"#(<p style="color:green"><b>EFIS data detected:</b> pitch and roll pre-populated from EFIS. Enter local field PAlt manually (set altimeter to 29.92 inHg and read).</p>)#";

sPage += R"#(
<div style="max-width: 720px; margin: 0 auto; padding: 12px;">
<br><b>Current sensor calibration:</b><br><br>)#" + sCurrentConfig + R"#(<br>
        <p style="color:black">This procedure will calibrate the system's accelerometers, gyros and pressure sensors.<br><br>
        <b>Requirements:</b><br><br>
        1. Do this configuration in no wind condition. Preferably inside a closed hangar, no moving air<br>
        2. Box orientation is set up properly in <a href="/aoaconfig">System Configuration</a><br>
        3. If the aircraft is not in a level attitude enter the current true pitch and roll angles below.<br>
        4. Enter current pressure altitude in feet. (Set your altimeter to 29.92 inHg and read the altitude)
        <br><br>
        Calibration will take a few seconds.
        </p>
        )#" + sEfisNote + R"#(
        <br>
        <br>
        <form action="sensorconfig" method="GET">
        <table>
        <tr><td><label>True Aircraft Pitch (degrees)</label></td>
        <td><input class="inputField" type="text" name="trueAircraftPitch" value=")#" + String(fDefPitch) + R"#("></td></tr>
        <tr><td><label>True Aircraft Roll (degrees)</label></td>
        <td><input class="inputField" type="text" name="trueAircraftRoll" value=")#" + String(fDefRoll) + R"#("></td></tr>
        <tr><td><label>True Aircraft Pressure Altitude (feet)</label></td>
        <td><input class="inputField" type="text" name="trueAircraftPalt" value=")#" + sDefPalt + R"#(" placeholder=")#" + sPaltPlaceholder + R"#(" required></td></tr>
        </table>

        <input type="hidden" name="confirm" value="yes">
        <br><br><br>
        <button type="submit" class="button">Calibrate Sensors</button>
        <a href="/">Cancel</a>
        </form>
</div>
)#";
        } // end if no confirm yes


    // Second time through with a confirm yes
    else
        {
        // PAlt is the calibration target for static-pressure bias, so an
        // empty submission would silently calibrate against a 0 ft truth
        // and bias the static sensor by ~1013 mb. Reject before any sensor
        // reads happen. Pitch/roll fall back to 0 if missing — that just
        // skips the bias delta, no destructive default.
        if (CfgServer.arg("trueAircraftPalt").length() == 0)
            {
            sPage += R"#(<br><br><p style="color:red"><b>Error:</b> Pressure altitude is required. Set your altimeter to 29.92 inHg and enter the indicated altitude in feet, or enter your local field elevation if you don't have an EFIS supplying baro.</p>)#";
            sPage += R"#(<br><a href="/sensorconfig">Back to sensor calibration</a>)#";
            sPage += pageFooter;
            CfgServer.send(400, "text/html", sPage);
            return;
            }

        float   fTrueAircraftPitch = 0.0;
        float   fTrueAircraftRoll  = 0.0;
        float   fTrueAircraftPalt  = 0;

        // Configure sensors
        if (CfgServer.arg("trueAircraftPitch") != "" &&
            CfgServer.arg("trueAircraftRoll")  != "" &&
            CfgServer.arg("trueAircraftPalt")  != "")
            {
            fTrueAircraftPitch = CfgServer.arg("trueAircraftPitch").toFloat();
            fTrueAircraftRoll  = CfgServer.arg("trueAircraftRoll").toFloat();
            fTrueAircraftPalt  = CfgServer.arg("trueAircraftPalt").toFloat();
            }
        else
            {
            fTrueAircraftPitch = 0.0;
            fTrueAircraftRoll  = 0.0;
            fTrueAircraftPalt  = 0.0;
            }

        //sdLogging=false;

        // Sample sensors
        long    lP45Total       = 0;        // counts
        long    lPFwdTotal      = 0;        // counts
        float   fPStaticTotal   = 0.0;      // millibars
        float   aVertTotal      = 0.00;
        float   aLatTotal       = 0.00;
        float   aFwdTotal       = 0.00;
        // Gyro biases are applied in raw IMU axes (fGyroX/Y/Z) before any
        // aircraft-orientation remapping/sign is applied. So measure biases in
        // raw axes here as well to avoid sign/mapping errors.
        float   fGyroXTotal      = 0.00;
        float   fGyroYTotal      = 0.00;
        float   fGyroZTotal      = 0.00;
        int     sensorReadCount = 150;

        for (int i=0; i < sensorReadCount; i++)
            {
            xSemaphoreTake(xSensorMutex, portMAX_DELAY);

            lP45Total     += g_pAOA->ReadPressureCounts();       // GetPressureP45();
            lPFwdTotal    += g_pPitot->ReadPressureCounts();     // GetPressurePfwd();
            fPStaticTotal += g_pStatic->ReadPressureMillibars(); // GetStaticPressure();

            g_pIMU->Read();
            aFwdTotal  += g_pIMU->Ax;   // All in aircraft orientation
            aLatTotal  += g_pIMU->Ay;
            aVertTotal += g_pIMU->Az;
            // Raw gyro rates in IMU axes (deg/sec), without bias correction
            fGyroXTotal += g_pIMU->fGyroX;
            fGyroYTotal += g_pIMU->fGyroY;
            fGyroZTotal += g_pIMU->fGyroZ;

            // Avoid a tight busy-wait inside the web handler; yield to keep WiFi/core-0 responsive.
            vTaskDelay(pdMS_TO_TICKS(5));
            xSemaphoreGive(xSensorMutex);
            }

        // Calculate pitch from averaged accelerometer reading, i.e. no bias adjustments
        float fCalcImuPitch = accelPitch(aFwdTotal / sensorReadCount, aLatTotal / sensorReadCount, aVertTotal / sensorReadCount);
        float fCalcImuRoll  = accelRoll (aFwdTotal / sensorReadCount, aLatTotal / sensorReadCount, aVertTotal / sensorReadCount);

        // Adjust bias, calculate a new bias
        g_Config.fPitchBias = fTrueAircraftPitch - fCalcImuPitch;
        g_Config.fRollBias  = fTrueAircraftRoll  - fCalcImuRoll;
        g_Log.printf(MsgLog::EnWebServer, MsgLog::EnDebug, "aircraftPitch: %.2f,aircraftRoll: %.2f,calcPitch: %.2f,calcRoll: %.2f\n",fTrueAircraftPitch,fTrueAircraftRoll,fCalcImuPitch,fCalcImuRoll);

        g_Config.iPFwdBias  = int((lPFwdTotal/sensorReadCount));
        g_Config.iP45Bias   = int((lP45Total/sensorReadCount));

        float fMeasuredStaticMB   = fPStaticTotal/sensorReadCount;
        float fCalculatedStaticMB = inhg2mb(29.92125535 * pow(((288 - (0.0065 * ft2m(fTrueAircraftPalt))) / 288), 5.2561)); // https://www.weather.gov/media/epz/wxcalc/stationPressure.pdf from inHg to milliBars.
        g_Config.fPStaticBias     = fMeasuredStaticMB - fCalculatedStaticMB;

        g_Log.printf(MsgLog::EnWebServer, MsgLog::EnDebug, "Measured Static %8.3f mb Calculated Static %8.3f mb Bias %6.3f\n", fMeasuredStaticMB, fCalculatedStaticMB, g_Config.fPStaticBias);

        // Biases are stored/applied in raw IMU axes.
        g_Config.fGxBias = -fGyroXTotal / sensorReadCount;
        g_Config.fGyBias = -fGyroYTotal / sensorReadCount;
        g_Config.fGzBias = -fGyroZTotal / sensorReadCount;

        g_Config.SaveConfigurationToFile();

        // Refresh IMU/AHRS after updating biases.
        // Init() recomputes the installation rotation matrix from the new
        // pitch/roll biases and re-initializes the attitude filter, matching
        // the pattern in HandleConfigSave().
        xSemaphoreTake(xSensorMutex, portMAX_DELAY);
        g_pIMU->Read();
        xSemaphoreGive(xSensorMutex);

        xSemaphoreTake(xAhrsMutex, portMAX_DELAY);
        g_AHRS.Init(kImuSampleRateHz);
        g_AHRS.Process();
        xSemaphoreGive(xAhrsMutex);

        //sdLogging=true;

        sPage += "<br><br><p>Sensors are now calibrated.</p>";
        sPage += "<br>The new parameters are:<br><br>";

        String sCurrentConfig = "";
        sCurrentConfig += "\n<table>\n";
        sCurrentConfig += "<tr><td style=\"padding-right: 20px;\">Pfwd Bias:</td><td style=\"text-align: right;\">"             + String(g_Config.iPFwdBias)     + "</td><td>Counts</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">P45 Bias:</td><td style=\"text-align: right;\">"              + String(g_Config.iP45Bias)      + "</td><td>Counts</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Measured Static:</td><td style=\"text-align: right;\">"       + String(fMeasuredStaticMB)      + "</td><td>millibars</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Calculated Static:</td><td style=\"text-align: right;\">"     + String(fCalculatedStaticMB)    + "</td><td>millibars</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Static Bias:</td><td style=\"text-align: right;\">"           + String(g_Config.fPStaticBias)  + "</td><td>millibars</td></tr>\n";

        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">gx Bias:</td><td style=\"text-align: right;\">"               + String(g_Config.fGxBias)       + "</td><td></td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">gy Bias:</td><td style=\"text-align: right;\">"               + String(g_Config.fGyBias)       + "</td><td></td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">gz Bias:</td><td style=\"text-align: right;\">"               + String(g_Config.fGzBias)       + "</td><td></td></tr>\n";

        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Current True AC Pitch:</td><td style=\"text-align: right;\">" + String(g_AHRS.PitchWithBias()) + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Pitch Bias:</td><td style=\"text-align: right;\">"            + String(g_Config.fPitchBias)    + "</td><td>Degrees</td></tr>\n";

        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Current True AC Roll:</td><td style=\"text-align: right;\">"  + String(g_AHRS.RollWithBias())  + "</td><td>Degrees</td></tr>\n";
        sCurrentConfig +=" <tr><td style=\"padding-right: 20px;\">Roll Bias:</td><td style=\"text-align: right;\">"             + String(g_Config.fRollBias)     + "</td><td>Degrees</td></tr>\n";

        sCurrentConfig +=" </table>\n";

        sPage += sCurrentConfig;

        } // end else save configure sensor values

    sPage += pageFooter;
    CfgServer.send(200, "text/html", sPage);

    } // end HandleSensorConfig()


// ----------------------------------------------------------------------------
void HandleWifiReflash()
    {
    String sPage;
    UpdateHeader();
    sPage.reserve(pageHeader.length() + 1024);
    sPage += pageHeader;
    sPage += "<br><br><p>Wifi reflash mode disables the Teensy's serial port to enable reflashing the Wifi chip via its microUSB port.\
    <br><br><span style=\"color:red\">This mode is now activated until reboot.</span></p>";
    sPage += pageFooter;
//    sendSerialCommand("$WIFIREFLASH!");
    CfgServer.send(200, "text/html", sPage);
    }

// ----------------------------------------------------------------------------

void HandleUpgrade()
    {
    ServePageStub(htmlStub_upgrade);
    }


// ----------------------------------------------------------------------------

void HandleUpgradeSuccess()
    {
    String sPage;
    UpdateHeader();
    sPage.reserve(pageHeader.length() + 2048);
    sPage += pageHeader;
    sPage += "<br><br><br><br><span style=\"color:black\">Firmware upgrade complete. Wait a few seconds until OnSpeed reboots.</span><br><br><br><br>";
    sPage += "<script>setInterval(function () { document.getElementById('rebootprogress').value+=0.1; document.getElementById('rebootprogress').innerHTML=document.getElementById('rebootprogress').value+'%'}, 10);setTimeout(function () { window.location.href = \"/\";}, 10000);</script>";
    sPage += "<div align=\"center\"><progress id=\"rebootprogress\" max=\"100\" value=\"0\"> 0% </progress></div>";

    sPage += pageFooter;
    CfgServer.send(200, "text/html", sPage);
    }

// ----------------------------------------------------------------------------

void HandleUpgradeFailure()
    {
    String sPage;
    UpdateHeader();
    sPage.reserve(pageHeader.length() + 1024);
    sPage += pageHeader;
    sPage += "<br><br><br><br><span style=\"color:red\">Firmware upgrade failed. Power cycle OnSpeed box and try again.</span><br><br><br><br>";
    sPage += pageFooter;
    CfgServer.send(200, "text/html", sPage);
    }

// ----------------------------------------------------------------------------

void HandleFormat()
    {
    ServePageStub(htmlStub_format);
    }



// ----------------------------------------------------------------------------

void HandleLogs()
    {
    ServePageStub(htmlStub_logs);
    }
 // end HandleLogs()


// ----------------------------------------------------------------------------

void HandleDelete()
    {
    String sFilename;

    // Handle case with no file name
    if (!CfgServer.hasArg("file"))
        {
//g_Log.printf("Delete missing file parameter\n");
        CfgServer.send(400, "text/plain", "Missing file parameter");
        return;
        }

    sFilename = CfgServer.arg("file");

    if (!IsSafeLogFilename(sFilename))
        {
        CfgServer.send(400, "text/plain", "Invalid filename");
        return;
        }

    // File delete not yet confirmed. We show the confirmation page even
    // if this file is currently active — the pilot might navigate away.
    // The active-file guard fires at the confirmed-delete step below,
    // under the same mutex as the remove, so the check+remove is atomic.
    if (CfgServer.arg("confirm").indexOf("yes") < 0)
        {
        String sPage;
        UpdateHeader();
        sPage.reserve(pageHeader.length() + 1024);
        sPage += pageHeader;

//g_Log.printf("Confirm delete %s\n", sFilename.c_str());

        // Display confirmation page — sFilename is safe (alphanumeric, dash,
        // underscore, dot) after IsSafeLogFilename, so no HTML escaping needed.
        sPage += "<br><br><p style=\"color:red\">Confirm that you want to delete <b>" + sFilename + "</b></p>\
        <br><br><br>\
        <a href=\"/delete?confirm=yes&file=" + sFilename + "\" class=\"button\">Delete</a>\
        <a href=\"/logs\">Cancel</a>";
        sPage += pageFooter;
        CfgServer.send(200, "text/html", sPage);
        }

    // File delete has been confirmed
    else
        {
        bool bWasActive = false;
        if (xSemaphoreTake(xWriteMutex, pdMS_TO_TICKS(100)))
            {
            // Check active-file guard under the same mutex as the remove,
            // so check+skip is atomic relative to LogSensor::Open/Close.
            if (IsActiveLogFile(sFilename))
                {
                bWasActive = true;
                }
            else
                {
                g_SdFileSys.remove(sFilename.c_str());
                // Also remove matching sidecar if it exists. Best-effort:
                // absent sidecar is fine.
                int iDot = sFilename.lastIndexOf('.');
                if (iDot > 0)
                    {
                    String sMeta = sFilename.substring(0, iDot) + ".meta";
                    if (g_SdFileSys.exists(sMeta.c_str()))
                        g_SdFileSys.remove(sMeta.c_str());
                    }
                }
            xSemaphoreGive(xWriteMutex);
            }

        if (bWasActive)
            {
            CfgServer.send(409, "text/plain",
                           "Cannot delete the log currently being written.");
            return;
            }

        CfgServer.sendHeader("Location", "/logs");
        CfgServer.send(301, "text/html", "");
        }

    }

// ----------------------------------------------------------------------------

void HandleDeleteBulk()
    {
    // Gather selected filenames. The form produced by HandleLogs submits
    // every checked box as a separate "f" argument. We only do the safe-
    // filename filter here; the active-file check is deferred to the delete
    // loop where it can be performed under xWriteMutex atomically with
    // the remove.
    std::vector<String> selected;
    for (int i = 0; i < CfgServer.args(); i++)
        {
        if (CfgServer.argName(i) == "f")
            {
            String v = CfgServer.arg(i);
            if (IsSafeLogFilename(v))
                selected.push_back(v);
            }
        }

    if (selected.empty())
        {
        CfgServer.sendHeader("Location", "/logs");
        CfgServer.send(301, "text/html", "");
        return;
        }

    // Not yet confirmed: show a confirmation page listing selected files.
    // Use a <table> for the filename list — the site's global CSS collapses
    // <ul> items into a single horizontal bar which smashes the filenames
    // together and is unreadable.
    if (CfgServer.arg("confirm").indexOf("yes") < 0)
        {
        String sPage;
        UpdateHeader();
        sPage.reserve(pageHeader.length() + 2048);
        sPage += pageHeader;
        sPage += "<br><br><p style=\"color:red;margin-left:10px\">Delete these ";
        sPage += String((unsigned)selected.size());
        sPage += " file(s)?</p>\n";
        sPage += "<form method=\"POST\" action=\"/delete-bulk\">\n";
        sPage += "<input type=\"hidden\" name=\"confirm\" value=\"yes\">\n";
        sPage += "<table style=\"margin-left:10px\">\n";
        for (const String& f : selected)
            {
            sPage += "<tr><td>";
            sPage += f;
            sPage += "</td></tr>\n";
            sPage += "<input type=\"hidden\" name=\"f\" value=\"";
            sPage += f;
            sPage += "\">\n";
            }
        sPage += "</table>\n";
        sPage += "<br><p style=\"margin-left:10px\">";
        sPage += "<button type=\"submit\" class=\"button\">Delete</button>\n";
        sPage += "&nbsp;&nbsp;<a href=\"/logs\" class=\"button\">Cancel</a>\n";
        sPage += "</p></form>\n";
        sPage += pageFooter;
        CfgServer.send(200, "text/html", sPage);
        return;
        }

    // Confirmed: delete each file + its matching sidecar.
    //
    // Large batches (user reported 164 files) used to:
    //   - hold xWriteMutex for 30-60+ seconds, blocking the logger writer,
    //   - starve the task watchdog on core 1,
    //   - cause a soft-reset, which opened a fresh log on restart.
    //
    // Mitigations:
    //   1. Pause the logger so it stops queueing rows during the batch —
    //      same pattern HandleLogs uses.
    //   2. Enumerate the existing .meta files ONCE, up front, while holding
    //      the mutex. This avoids N fruitless exists() calls in the loop;
    //      each exists() is itself a directory walk on FAT.
    //   3. Release and re-take xWriteMutex between files and yield via
    //      vTaskDelay(1) so the logger drain task can run, the web server
    //      can service other clients, and the watchdog stays happy.
    struct PauseGuard
        {
        bool bPrevPause;
        PauseGuard() : bPrevPause(g_bPause) { g_bPause = true; }
        ~PauseGuard() { g_bPause = bPrevPause; }
        } pauseGuard;

    // Delete each file one at a time, yielding between iterations. For
    // each csv we attempt to remove the matching .meta unconditionally —
    // SdFat's remove() on a missing file is a near no-op (single directory
    // probe) and we avoid any snapshot-staleness concerns if a new sidecar
    // lands between enumeration and delete.
    //
    // The active-file guard is inside the mutex so the check and remove
    // are atomic w.r.t. LogSensor::Open/Close. If a log that was inactive
    // at form-submit time has become active (pilot rotated logs between
    // confirmation and execution — very narrow window), skip that file
    // silently rather than deleting a live log.
    for (const String& f : selected)
        {
        if (xSemaphoreTake(xWriteMutex, pdMS_TO_TICKS(2000)))
            {
            if (!IsActiveLogFile(f))
                {
                g_SdFileSys.remove(f.c_str());

                int iDot = f.lastIndexOf('.');
                if (iDot > 0)
                    {
                    String sMeta = f.substring(0, iDot) + ".meta";
                    // Ignore return value — absent sidecar is fine.
                    g_SdFileSys.remove(sMeta.c_str());
                    }
                }
            xSemaphoreGive(xWriteMutex);
            }
        // Yield so the logger drain task, web server, and watchdog all
        // get CPU between deletes. One tick is enough.
        vTaskDelay(1);
        }

    CfgServer.sendHeader("Location", "/logs");
    CfgServer.send(301, "text/html", "");
    }

// ----------------------------------------------------------------------------

void HandleDownload()
    {
    FsFile file;

    if (!CfgServer.hasArg("file"))
        {
        CfgServer.send(400, "text/plain", "Missing file parameter");
        return;
        }

    String sRawName = CfgServer.arg("file");
    if (!IsSafeLogFilename(sRawName))
        {
        CfgServer.send(400, "text/plain", "Invalid filename");
        return;
        }
    String sFilename = "/" + sRawName;

    // Pause logging during downloads to avoid SD mutex contention and
    // incomplete transfers (and to match the UI guidance on the index page).
    struct PauseGuard
        {
        bool bPrevPause;
        PauseGuard() : bPrevPause(g_bPause) { g_bPause = true; }
        ~PauseGuard() { g_bPause = bPrevPause; }
        } pauseGuard;

    size_t fileSize = 0;
    if (xSemaphoreTake(xWriteMutex, pdMS_TO_TICKS(2000)))
        {
        file = g_SdFileSys.open(sFilename.c_str(), O_READ);
        if (file)
            fileSize = file.size();
        xSemaphoreGive(xWriteMutex);
        }
    else
        {
        CfgServer.send(503, "text/plain", "SD busy");
        return;
        }

    if (!file)
        {
        CfgServer.send(404, "text/plain", "File not found");
        return;
        }

    // Send headers to trigger download
    CfgServer.setContentLength(fileSize);
    CfgServer.sendHeader("Content-Type", "application/octet-stream");
    // Use the validated local, not a second CfgServer.arg() call, so the
    // Content-Disposition header is guaranteed to reflect the validated name.
    CfgServer.sendHeader("Content-Disposition", "attachment; filename=" + sRawName);
    CfgServer.sendHeader("Connection", "close");
    CfgServer.send(200);
//      CfgServer.send(200, "application/octet-stream", "");

    WiFiClient client = CfgServer.client();
    uint8_t achBuffer[1460];
    while (true)
        {
        size_t iLen = 0;
        // Getting and giving the semaphore is a bit slow
        // but wrapping this in one take / give doesn't speed
        // things that much and not having the sepaphore messes up logging.
        if (xSemaphoreTake(xWriteMutex, pdMS_TO_TICKS(2000)))
            {
            iLen = file.read(achBuffer, sizeof(achBuffer));
            xSemaphoreGive(xWriteMutex);
            }
        else
            {
            // SD is busy; wait and retry rather than aborting mid-transfer.
            if (!client.connected())
                break;
            vTaskDelay(pdMS_TO_TICKS(10));
            continue;
            }

        if (iLen == 0)
            break;

        size_t iWritten = 0;
        while (iWritten < iLen)
            {
            size_t iThisWrite = client.write(achBuffer + iWritten, iLen - iWritten);
            if (iThisWrite == 0)
                {
                if (!client.connected())
                    {
                    iWritten = 0;
                    break;
                    }
                // Yield and retry.
                vTaskDelay(pdMS_TO_TICKS(1));
                continue;
                }
            iWritten += iThisWrite;
            // Yield periodically to keep WiFi/core-0 responsive during large transfers.
            delay(0);
            }

        if (iWritten != iLen)
            break;
        }

    if (xSemaphoreTake(xWriteMutex, pdMS_TO_TICKS(100)))
        {
        file.close();
        xSemaphoreGive(xWriteMutex);
        }

    } // end HandleDownload()


// ----------------------------------------------------------------------------

#if 0
bool HandleFileRead(String path) {

  String lengthString=CfgServer.arg("length");
  if (lengthString=="")
      {
      CfgServer.send(500, "text/plain", "Invalid Request");
                  return true;
      }

  String fileName=path.substring(1,path.indexOf("?")-1);
  unsigned long contentLength=atol(lengthString.c_str());
  delay(200);
  sendSerialCommand("$PRINT ");
  sendSerialCommand(fileName); // skip the slash in front of the file
  sendSerialCommand("!"); // finish the print command to grab the file via serial
  CfgServer.setContentLength(contentLength);
  CfgServer.sendHeader("Content-Disposition", "attachment; filename="+fileName);
  if (fileName.indexOf(".csv")>=0) CfgServer.send(200, "text/csv", ""); // send empty string (headers only)
      else CfgServer.send(200, "text/plain", "");

  unsigned long starttime=millis();
  unsigned long bytecount=0;
  //String sendBuffer;
  char sendBuffer[1461];
  int sendBufferIndex=0;
  byte checksum;
  int fullPacketCount=contentLength/1459;
  int endPacketSize=contentLength-fullPacketCount*1459;
  int packetCount=0;

  while (packetCount<fullPacketCount+1) // full packets + 1 partial packet
  {
  if (Serial.available()>0)
      {
       char inChar=Serial.read();
       if (inChar==0xFF && sendBufferIndex<1459) continue; // filter out FF junk (esp32 issue in this version)
       sendBuffer[sendBufferIndex]=inChar;
       sendBufferIndex++;

       if (sendBufferIndex==5 && strstr(sendBuffer, "<404>"))
                  {
                  // file does not exist
                  CfgServer.send(404, "text/plain", "File Not Found");
                  // lower Wifi power after file transfer completed
                  delay(200);
                  Serial.println("404");
                  return true;
                  }

       if (sendBufferIndex==1460 || (sendBufferIndex==endPacketSize+1 && packetCount==fullPacketCount))
        {
        checksum=0;
        for (int i=0;i<sendBufferIndex-1;i++)
           {
           checksum+=sendBuffer[i];
           }
        Serial.write(checksum);
        Serial.flush(true); // flush TX only

        if (checksum==sendBuffer[sendBufferIndex-1])
              {
               packetCount++; // got one packet, correct checksum
               CfgServer.sendContent(sendBuffer,sendBufferIndex-1);
              }
        sendBufferIndex=0;
        }
       starttime=millis();
      }

  if ((millis()-starttime)>5000)
      {
      // SD read timeout
      delay(200);
      Serial.println("Receive Timeout");
      return false;
      }
  }
  // lower Wifi power after file transfer completed
  //if (sendBufferIndex>0) CfgServer.sendContent(sendBuffer,sendBufferIndex-1); // send the remaining characters in buffer
  return true;
}

#endif

// ----------------------------------------------------------------------------
// Utility Functions
// ----------------------------------------------------------------------------

#if 0
String getConfigString()
{
// get configstring
sendSerialCommand("$STOPLIVEDATA!");
delay(200);

//Serial.flush();
sendSerialCommand("$SENDCONFIGSTRING!");
String sConfigString="";
unsigned long starttime=millis();
while (true)
  {
  if (Serial.available()>0)
      {
       char inChar=Serial.read();
       sConfigString+=inChar;
       starttime=millis();  // reset timeout
       if (sConfigString.indexOf("</CHECKSUM>")>0)
          {
           String checksumString=getConfigValue(sConfigString,"CHECKSUM");
           String configContent=getConfigValue(sConfigString,"CONFIG");
           // calc CRC
           int16_t calcCRC;
           for (unsigned int i=0;i<configContent.length();i++) calcCRC+=configContent[i];
              if (String(calcCRC,HEX)==checksumString)
                 {
                 // checksum match
                  return sConfigString;
                 } else return "BAD CHECKSUM:"+sConfigString; // checksum error
          }
      }
  // timeout
  if ((millis()-starttime)>3000)
      {
      return "TIMEOUT"; // don't return partial configstring when timeout occurs
      }
  }
return sConfigString;
}

// ----------------------------------------------------------------------------

String getDefaultConfigString()
{
// get configstring
//Serial.flush();
sendSerialCommand("$SENDDEFAULTCONFIGSTRING!");
String sConfigString="";
unsigned long starttime=millis();
while (true)
  {
  if (Serial.available()>0)
      {
       char inChar=Serial.read();
       sConfigString+=inChar;
       starttime=millis();  // reset timeout
       if (sConfigString.indexOf("</CHECKSUM>")>0)
          {
           String checksumString=getConfigValue(sConfigString,"CHECKSUM");
           String configContent=getConfigValue(sConfigString,"CONFIG");
           // calc CRC
           int16_t calcCRC;
           for (unsigned int i=0;i<configContent.length();i++) calcCRC+=configContent[i];
           if (String(calcCRC,HEX)==checksumString)
                 {
                 // checksum match
                 return sConfigString;
                 } else return ""; // checksum error
          }
      }
  // timeout
  if ((millis()-starttime)>2000)
      {
      return ""; // don't return partial configstring when timeout occurs
      }
  }
return sConfigString;
}

// ----------------------------------------------------------------------------

bool setConfigString(String &sConfigString)
{
//Serial.flush();
// add CRC to sConfigString
addCRC(sConfigString);

sendSerialCommand("$SAVECONFIGSTRING"+sConfigString+"!");

unsigned long starttime=millis();
// wait for ACK
String responseString;
while (true)
      {
      //wait 2 seconds to confirm saveConfigSting
      if (Serial.available()>0)
         {
         char inChar=Serial.read();
         responseString+=inChar;
         if (responseString.indexOf("</CONFIGSAVED>")>=0) return true;
         if (responseString.indexOf("</CONFIGERROR>")>=0) return false;
         }

      // timeout
      if ((millis()-starttime)>3000)
          {
          return false; // timeout
          }
      }
return false;
}
#endif

