#!/usr/bin/env python3
"""Render assets/onspeed_logo.svg into lib/assets/OnSpeedLogo.h.

Reads the source SVG, renders it at high resolution with thickened strokes
(the source uses stroke-width=0.24 which aliases away at small sizes),
trims whitespace, downsamples to a target box with anti-aliasing, inverts
to white-on-black, and emits an RGB565 PROGMEM array for M5GFX pushImage().

Run when the source SVG changes; the output header is checked in so the
firmware build does not depend on rsvg/ImageMagick at compile time.

Usage: python3 scripts/gen_logo_header.py
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

TARGET_SIZE = 120  # pixels, square (gauge mark only)
RENDER_WIDTH = 2400  # high-res render before downsampling
STROKE_WIDTH = 1.6  # SVG units; source is 0.24, thicken for visibility
# Crop the top fraction of the trimmed render to drop the embedded
# "FlyOnSpeed / ANGLE OF ATTACK" wordmark — that text gets re-drawn
# with M5GFX fonts on the splash, which is sharper than rasterizing
# the SVG glyphs at this size.
WORDMARK_CROP_FRACTION = 0.66  # keep top 66% of trimmed bounding box
# No binarization: the splash uses a 16-bit RGB565 sprite (not the
# 8-bit palette sprite the live display uses), so anti-aliased
# grayscale edges render cleanly without dither speckle.

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
SRC_SVG = PROJECT / "assets" / "onspeed_logo.svg"
OUT_HEADER = PROJECT / "lib" / "assets" / "OnSpeedLogo.h"


def need(cmd: str) -> str:
    path = shutil.which(cmd)
    if path is None:
        sys.exit(f"required tool not found on PATH: {cmd}")
    return path


def thicken_strokes(svg_text: str, new_width: float) -> str:
    """Replace every stroke-width="…" with new_width."""
    return re.sub(
        r'stroke-width="[^"]+"',
        f'stroke-width="{new_width}"',
        svg_text,
    )


def main() -> int:
    rsvg = need("rsvg-convert")
    magick = need("magick")

    if not SRC_SVG.exists():
        sys.exit(f"source SVG missing: {SRC_SVG}")

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)

    svg_text = SRC_SVG.read_text(encoding="utf-8")
    thick = thicken_strokes(svg_text, STROKE_WIDTH)

    work = PROJECT / ".logo-build"
    work.mkdir(exist_ok=True)
    thick_svg = work / "thick.svg"
    raw_png = work / "raw.png"
    final_png = work / "final.png"
    rgba_bin = work / "final.rgba"
    thick_svg.write_text(thick, encoding="utf-8")

    subprocess.run(
        [rsvg, str(thick_svg), "-w", str(RENDER_WIDTH), "-o", str(raw_png)],
        check=True,
    )

    # Pipeline order matters:
    #   1. Trim transparent margins (rsvg pads to source viewBox).
    #   2. Composite over WHITE so strokes (black) stay visible after alpha
    #      drop. Compositing over black would collapse strokes into the
    #      background and produce a uniform black image.
    #   3. Negate so strokes become white on black for the M5 splash.
    #   4. Crop the wordmark off — gauge mark only — and re-trim.
    #   5. Downsample with Lanczos to preserve stroke anti-aliasing.
    #   6. Threshold to pure black/white so the 8-bit palette downconversion
    #      in main.cpp can't dither soft gray edges into colored speckle.
    #   7. Pad to square against black for a clean final canvas.
    crop_pct = int(round(WORDMARK_CROP_FRACTION * 100))
    subprocess.run(
        [
            magick,
            str(raw_png),
            "-trim",
            "+repage",
            "-background", "white",
            "-alpha", "remove",
            "-negate",
            "-gravity", "north",
            "-crop", f"x{crop_pct}%+0+0",
            "+repage",
            "-trim",
            "+repage",
            "-filter", "Lanczos",
            "-resize", f"{TARGET_SIZE}x{TARGET_SIZE}",
            "-gravity", "center",
            "-background", "black",
            "-extent", f"{TARGET_SIZE}x{TARGET_SIZE}",
            str(final_png),
        ],
        check=True,
    )

    # Dump pixels as raw RGBA (8-bit per channel) for deterministic packing.
    subprocess.run(
        [magick, str(final_png), "-depth", "8", str(rgba_bin)],
        check=True,
    )

    raw = rgba_bin.read_bytes()
    expected = TARGET_SIZE * TARGET_SIZE * 4
    if len(raw) != expected:
        sys.exit(f"unexpected RGBA byte count: got {len(raw)}, want {expected}")

    pixels: list[int] = []
    for i in range(0, len(raw), 4):
        r, g, b, _ = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        pixels.append(rgb565)

    lines = []
    lines.append("// Auto-generated by software/OnSpeed-M5-Display/scripts/gen_logo_header.py")
    lines.append("// Source: assets/onspeed_logo.svg")
    lines.append("// Do not edit by hand. Re-run the script if the SVG changes.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#ifdef ESP_PLATFORM")
    lines.append("#include <pgmspace.h>")
    lines.append("#else")
    lines.append("#define PROGMEM")
    lines.append("#endif")
    lines.append("")
    lines.append(f"static constexpr int kOnSpeedLogoWidth  = {TARGET_SIZE};")
    lines.append(f"static constexpr int kOnSpeedLogoHeight = {TARGET_SIZE};")
    lines.append("")
    lines.append("// White-on-black RGB565, row-major, big-endian channel order matching")
    lines.append("// M5GFX's default pushImage(uint16_t*) interpretation.")
    lines.append(
        f"static const uint16_t kOnSpeedLogo[{TARGET_SIZE * TARGET_SIZE}] PROGMEM = {{"
    )

    # 12 values per line, hex-formatted, indented 2 spaces.
    per_line = 12
    for chunk_start in range(0, len(pixels), per_line):
        chunk = pixels[chunk_start:chunk_start + per_line]
        body = ", ".join(f"0x{p:04X}" for p in chunk)
        suffix = "," if chunk_start + per_line < len(pixels) else ""
        lines.append(f"  {body}{suffix}")

    lines.append("};")
    lines.append("")
    OUT_HEADER.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_HEADER} ({TARGET_SIZE}x{TARGET_SIZE}, {len(pixels) * 2} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
