"""Subprocess wrapper for host_main ahrs_tone in --input-format=sdlog mode.

Used by tune_ekf.py when --driver=host-main is selected. Writes the
trial's EKFQConfig + PipelineQuatConfig to a temporary kv file, invokes
host_main, parses the CSV output into a pandas DataFrame, and returns
it for downstream composite_loss scoring.

Loss math stays in Python; this wrapper is pure I/O + parameter
marshalling.
"""

from __future__ import annotations

import io
import subprocess
import tempfile
from pathlib import Path
from typing import Sequence

import pandas as pd

from onspeed_ekf import EKFQConfig, PipelineQuatConfig


# Mapping from Python field names to the kv-file keys host_main expects.
_KV_KEYS: tuple[tuple[str, str], ...] = (
    ("q_quat", "q_quat"),
    ("q_bias", "q_bias"),
    ("q_z", "q_z"),
    ("q_vz", "q_vz"),
    ("q_b_az", "q_b_az"),
    ("q_beta", "q_beta"),
    ("r_ax", "r_ax"),
    ("r_ay", "r_ay"),
    ("r_az", "r_az"),
    ("r_baro", "r_baro"),
    ("r_beta_prior", "r_beta_prior"),
    ("r_bias_prior", "r_bias_prior"),
    ("k_beta_R", "k_beta_r"),
    ("p_quat", "p_quat"),
    ("p_bias", "p_bias"),
    ("p_z", "p_z"),
    ("p_vz", "p_vz"),
    ("p_b_az", "p_b_az"),
    ("p_beta", "p_beta"),
    ("tas_min_mps", "tas_min_mps"),
)

_PIPE_KV_KEYS: tuple[tuple[str, str], ...] = (
    ("accel_ema_alpha", "accel_ema_alpha"),
    ("comp_fade_tau_sec", "comp_fade_tau_sec"),
    ("ias_alive_kt", "ias_gate_rising_kt"),
    ("tasdot_ema_alpha", "tasdot_ema_alpha"),
)


def _write_kv(ekfq_cfg: EKFQConfig, pipe_cfg: PipelineQuatConfig, path: Path) -> None:
    lines = ["# Auto-generated by run_host_main.py"]
    for py_attr, kv_key in _KV_KEYS:
        v = getattr(ekfq_cfg, py_attr)
        lines.append(f"{kv_key}={v!r}")
    for py_attr, kv_key in _PIPE_KV_KEYS:
        v = getattr(pipe_cfg, py_attr)
        lines.append(f"{kv_key}={v!r}")
    path.write_text("\n".join(lines) + "\n")


def run_host_main(
    host_main_path: Path,
    log_path: Path,
    config_path: Path,
    ekfq_cfg: EKFQConfig,
    pipe_cfg: PipelineQuatConfig,
    passthrough_cols: Sequence[str],
) -> pd.DataFrame:
    """Invoke host_main ahrs_tone for one Optuna trial."""
    with tempfile.TemporaryDirectory() as td:
        kv_path = Path(td) / "trial.kv"
        _write_kv(ekfq_cfg, pipe_cfg, kv_path)
        argv = [
            str(host_main_path), "ahrs_tone",
            "--algorithm", "ekfq",
            "--input-format", "sdlog",
            "--input", str(log_path),
            "--config", str(config_path),
            "--ekfq-config", str(kv_path),
            "--passthrough-cols", ",".join(passthrough_cols),
        ]
        proc = subprocess.run(argv, capture_output=True, text=True)
        if proc.returncode != 0:
            raise RuntimeError(
                f"host_main ahrs_tone exited {proc.returncode}: "
                f"{proc.stderr[-1000:]}"
            )
        return pd.read_csv(io.StringIO(proc.stdout))
