// AUTO-GENERATED by scripts/build_web_bundle.py — DO NOT EDIT.
//
// Per-page HTML stubs for Preact-served pages.  Each stub is a
// complete document; ConfigWebServer's ServePageStub() handler
// sends it as-is.  The shared JS / CSS bundles live at
// /static/app-<etag>.{js,css} with immutable cache.

#pragma once
#include <pgmspace.h>

static const char htmlStub_indexer[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Indexer</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="indexer"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_calwiz[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Calibration</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="calwiz"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_home[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Home</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="home"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_reboot[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Reboot</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="reboot"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_format[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Format SD</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="format"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_upgrade[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Firmware Upgrade</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="upgrade"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_logs[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="onspeed-version" content="{{onspeedVersion}}">
<title>OnSpeed — Logs</title>
<link rel="stylesheet" href="/static/app-ce5fb7c0195c.css">
</head>
<body>
<noscript><p>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</p><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></noscript><div id="app" data-page="logs"></div>
<script src="/static/app-004a57225279.js" defer></script>
</body>
</html>)=====";

