// AUTO-GENERATED by scripts/build_web_bundle.py — DO NOT EDIT.
//
// Per-page HTML stubs for Preact-served pages.  Each stub is a
// complete document; ConfigWebServer's ServePageStub() handler
// sends it as-is.  The shared JS / CSS bundles live at
// /static/app-<etag>.{js,css} with immutable cache.

#pragma once
#include <pgmspace.h>

static const char htmlStub_indexer[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OnSpeed — Indexer</title>
<link rel="stylesheet" href="/static/app-5191f00d011e.css">
</head>
<body>
<div id="app" data-page="indexer"><noscript>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</noscript><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></div>
<script src="/static/app-87f37c5e4547.js" defer></script>
</body>
</html>)=====";

static const char htmlStub_calwiz[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OnSpeed — Calibration</title>
<link rel="stylesheet" href="/static/app-5191f00d011e.css">
</head>
<body>
<div id="app" data-page="calwiz"><noscript>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</noscript><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></div>
<script src="/static/app-87f37c5e4547.js" defer></script>
</body>
</html>)=====";

