// AUTO-GENERATED by scripts/build_web_bundle.py — DO NOT EDIT.
//
// Legacy include path.  The page stub now lives in html_stubs.h
// as htmlStub_indexer; this header is preserved as a thin
// definition so any stale `#include "Web/html_indexer.h"` keeps
// compiling during the migration.  Delete after PR 1 has
// settled.

#pragma once
#include <pgmspace.h>

static const char htmlIndexer[] PROGMEM = R"=====(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OnSpeed — Indexer</title>
<link rel="stylesheet" href="/static/app-5191f00d011e.css">
</head>
<body>
<div id="app" data-page="indexer"><noscript>OnSpeed configuration requires JavaScript. Use one of the links below to navigate.</noscript><nav class="onspeed-fallback-nav" aria-label="fallback"><a href="/">Home</a> | <a href="/indexer">Indexer</a> | <a href="/aoaconfig">Config</a> | <a href="/calwiz">Calibration</a> | <a href="/logs">Logs</a> | <a href="/upgrade">Upgrade</a> | <a href="/reboot">Reboot</a></nav></div>
<script src="/static/app-d50f3dc82cee.js" defer></script>
</body>
</html>)=====";
