// AUTO-GENERATED by scripts/build_web_bundle.py — DO NOT EDIT.
//
// Source: tools/web/legacy-pages/.  Each template keeps its
// {{name}} markers; ConfigWebServer.cpp substitutes them per
// request before sending the page.

// The .h declares; the paired legacy_pages.cpp defines.  This
// keeps the ~50 KB PROGMEM blobs from duplicating across
// translation units if another source ever pulls this header
// in alongside ConfigWebServer.cpp.

#pragma once
#include <pgmspace.h>

extern const char legacy_aoaconfig_html[] PROGMEM;
extern const char legacy_aoaconfig_js[] PROGMEM;
extern const char legacy_aoaconfig_post_js[] PROGMEM;

