#!/usr/bin/env bash
# embed_sim_for_firmware.sh — produce gzipped PROGMEM headers of the
# M5 sim's live-data WASM artifacts so the Gen3 firmware can serve them
# from `/sim/index.{js,wasm}` for the on-device Indexer tab.
#
# Pipeline:
#   1. Run the M5 sim live build (build_wasm.sh --target live).
#   2. gzip -9 each output file.
#   3. xxd -i to convert into C arrays under
#      software/OnSpeed-Gen3-ESP32/Web/sim_index_*.h
#
# The .h files are gitignored — every contributor regenerates locally.
# A PIO pre-build hook (scripts/embed_sim_prebuild.py) runs this script
# only when its input source mtimes are newer than the .h mtimes, so a
# typical edit-and-build cycle on unrelated firmware code does not pay
# the emscripten cost.
#
# Prerequisites:
#   - emscripten (emcc on PATH)
#   - gzip, xxd
#   - PlatformIO has previously installed the M5 native env libdeps
#     (the live build reuses .pio/libdeps/native/M5Unified|M5GFX).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
M5_DIR="${REPO_ROOT}/software/OnSpeed-M5-Display"
SIM_DIR="${M5_DIR}/sim"
WEB_DIR="${REPO_ROOT}/software/OnSpeed-Gen3-ESP32/Web"

LIVE_OUT_DIR="${SIM_DIR}/build/wasm-live"

if ! command -v emcc >/dev/null 2>&1; then
    echo "[embed-sim] ERROR: emcc not found on PATH." >&2
    echo "[embed-sim] Install with: brew install emscripten   (macOS)" >&2
    echo "[embed-sim] Or follow https://emscripten.org/docs/getting_started/downloads.html" >&2
    exit 1
fi

# build_wasm.sh reuses the M5 native env's libdeps cache. Populate it
# the first time without doing the full native compile.
if [[ ! -d "${M5_DIR}/.pio/libdeps/native/M5Unified" ]]; then
    echo "[embed-sim] Installing M5 native env libdeps (one-time)..."
    pio pkg install -e native --project-dir "${M5_DIR}" >/dev/null
fi

echo "[embed-sim] Building sim_live WASM..."
"${SIM_DIR}/build_wasm.sh" --target live >/dev/null

# Convert one binary file into a PROGMEM header with C array.
# $1 = input path, $2 = output header path, $3 = symbol base name.
emit_header() {
    local in_path="$1"
    local out_path="$2"
    local sym="$3"
    local tmp_gz
    tmp_gz="$(mktemp -t embed_sim.XXXXXX.gz)"
    gzip -9 -c "${in_path}" > "${tmp_gz}"

    local raw_size gz_size
    raw_size=$(wc -c < "${in_path}" | tr -d ' ')
    gz_size=$(wc -c < "${tmp_gz}" | tr -d ' ')

    {
        printf '// Auto-generated by scripts/embed_sim_for_firmware.sh — do not edit.\n'
        printf '// Gzipped %s. Served with Content-Encoding: gzip.\n' "${in_path##*/}"
        printf '// Raw size: %s bytes. Gzipped: %s bytes.\n\n' "${raw_size}" "${gz_size}"
        printf '#pragma once\n\n'
        printf '#include <pgmspace.h>\n#include <cstddef>\n#include <cstdint>\n\n'
        # xxd -i -n emits "unsigned char SYM[] = { ... };" plus
        # "unsigned int SYM_len = N;". sed rewrites to the typed,
        # PROGMEM-qualified inline declarations the firmware expects.
        xxd -i -n "${sym}_gz" < "${tmp_gz}" \
            | sed -e "s/^unsigned char ${sym}_gz\[\] = {/inline const uint8_t ${sym}_gz[] PROGMEM = {/" \
                  -e "s/^unsigned int ${sym}_gz_len = /inline const size_t ${sym}_gz_len = /"
    } > "${out_path}"

    rm -f "${tmp_gz}"
    printf '[embed-sim]   wrote %s (%s bytes raw, %s bytes gz)\n' \
        "${out_path}" "${raw_size}" "${gz_size}"
}

mkdir -p "${WEB_DIR}"
emit_header "${LIVE_OUT_DIR}/index.js"   "${WEB_DIR}/sim_index_js.h"   "kSimIndexJs"
emit_header "${LIVE_OUT_DIR}/index.wasm" "${WEB_DIR}/sim_index_wasm.h" "kSimIndexWasm"

echo "[embed-sim] Done."
